// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: codefly/services/tooling/v0/tooling.proto

package v0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tooling_ListSymbols_FullMethodName      = "/codefly.services.tooling.v0.Tooling/ListSymbols"
	Tooling_GetDiagnostics_FullMethodName   = "/codefly.services.tooling.v0.Tooling/GetDiagnostics"
	Tooling_GoToDefinition_FullMethodName   = "/codefly.services.tooling.v0.Tooling/GoToDefinition"
	Tooling_FindReferences_FullMethodName   = "/codefly.services.tooling.v0.Tooling/FindReferences"
	Tooling_RenameSymbol_FullMethodName     = "/codefly.services.tooling.v0.Tooling/RenameSymbol"
	Tooling_GetHoverInfo_FullMethodName     = "/codefly.services.tooling.v0.Tooling/GetHoverInfo"
	Tooling_GetCompletions_FullMethodName   = "/codefly.services.tooling.v0.Tooling/GetCompletions"
	Tooling_Fix_FullMethodName              = "/codefly.services.tooling.v0.Tooling/Fix"
	Tooling_ApplyEdit_FullMethodName        = "/codefly.services.tooling.v0.Tooling/ApplyEdit"
	Tooling_ListDependencies_FullMethodName = "/codefly.services.tooling.v0.Tooling/ListDependencies"
	Tooling_AddDependency_FullMethodName    = "/codefly.services.tooling.v0.Tooling/AddDependency"
	Tooling_RemoveDependency_FullMethodName = "/codefly.services.tooling.v0.Tooling/RemoveDependency"
	Tooling_GetProjectInfo_FullMethodName   = "/codefly.services.tooling.v0.Tooling/GetProjectInfo"
	Tooling_GetCallGraph_FullMethodName     = "/codefly.services.tooling.v0.Tooling/GetCallGraph"
	Tooling_Build_FullMethodName            = "/codefly.services.tooling.v0.Tooling/Build"
	Tooling_Test_FullMethodName             = "/codefly.services.tooling.v0.Tooling/Test"
	Tooling_Lint_FullMethodName             = "/codefly.services.tooling.v0.Tooling/Lint"
)

// ToolingClient is the client API for Tooling service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Tooling provides language-specific code operations.
// Every language agent (go-grpc, python-fastapi, etc.) implements this service.
//
// NOTE: File operations (read, write, list, search) and git operations are
// NOT part of this service. Mind handles those directly via its VFS.
type ToolingClient interface {
	// LSP operations
	ListSymbols(ctx context.Context, in *ListSymbolsRequest, opts ...grpc.CallOption) (*ListSymbolsResponse, error)
	// GetDiagnostics returns compiler, linter, or language-server diagnostics.
	GetDiagnostics(ctx context.Context, in *GetDiagnosticsRequest, opts ...grpc.CallOption) (*GetDiagnosticsResponse, error)
	// GoToDefinition resolves the declaration for a symbol at a source position.
	GoToDefinition(ctx context.Context, in *GoToDefinitionRequest, opts ...grpc.CallOption) (*GoToDefinitionResponse, error)
	// FindReferences resolves usage locations for a symbol at a source position.
	FindReferences(ctx context.Context, in *FindReferencesRequest, opts ...grpc.CallOption) (*FindReferencesResponse, error)
	// RenameSymbol applies a language-aware rename across the service.
	RenameSymbol(ctx context.Context, in *RenameSymbolRequest, opts ...grpc.CallOption) (*RenameSymbolResponse, error)
	// GetHoverInfo returns hover documentation and type information.
	GetHoverInfo(ctx context.Context, in *GetHoverInfoRequest, opts ...grpc.CallOption) (*GetHoverInfoResponse, error)
	// GetCompletions returns completion suggestions at a source position.
	GetCompletions(ctx context.Context, in *GetCompletionsRequest, opts ...grpc.CallOption) (*GetCompletionsResponse, error)
	// Code modification
	Fix(ctx context.Context, in *FixRequest, opts ...grpc.CallOption) (*FixResponse, error)
	// ApplyEdit applies a smart edit and optional language fixers.
	ApplyEdit(ctx context.Context, in *ApplyEditRequest, opts ...grpc.CallOption) (*ApplyEditResponse, error)
	// Dependency management
	ListDependencies(ctx context.Context, in *ListDependenciesRequest, opts ...grpc.CallOption) (*ListDependenciesResponse, error)
	// AddDependency installs a package through the native package manager.
	AddDependency(ctx context.Context, in *AddDependencyRequest, opts ...grpc.CallOption) (*AddDependencyResponse, error)
	// RemoveDependency removes a package through the native package manager.
	RemoveDependency(ctx context.Context, in *RemoveDependencyRequest, opts ...grpc.CallOption) (*RemoveDependencyResponse, error)
	// Analysis
	GetProjectInfo(ctx context.Context, in *GetProjectInfoRequest, opts ...grpc.CallOption) (*GetProjectInfoResponse, error)
	// GetCallGraph runs whole-program call graph analysis.
	GetCallGraph(ctx context.Context, in *GetCallGraphRequest, opts ...grpc.CallOption) (*GetCallGraphResponse, error)
	// Dev validation
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
	// Test runs native tests and returns structured counts.
	Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
	// Lint runs native linting and returns structured diagnostics.
	Lint(ctx context.Context, in *LintRequest, opts ...grpc.CallOption) (*LintResponse, error)
}

type toolingClient struct {
	cc grpc.ClientConnInterface
}

func NewToolingClient(cc grpc.ClientConnInterface) ToolingClient {
	return &toolingClient{cc}
}

func (c *toolingClient) ListSymbols(ctx context.Context, in *ListSymbolsRequest, opts ...grpc.CallOption) (*ListSymbolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSymbolsResponse)
	err := c.cc.Invoke(ctx, Tooling_ListSymbols_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) GetDiagnostics(ctx context.Context, in *GetDiagnosticsRequest, opts ...grpc.CallOption) (*GetDiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiagnosticsResponse)
	err := c.cc.Invoke(ctx, Tooling_GetDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) GoToDefinition(ctx context.Context, in *GoToDefinitionRequest, opts ...grpc.CallOption) (*GoToDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoToDefinitionResponse)
	err := c.cc.Invoke(ctx, Tooling_GoToDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) FindReferences(ctx context.Context, in *FindReferencesRequest, opts ...grpc.CallOption) (*FindReferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindReferencesResponse)
	err := c.cc.Invoke(ctx, Tooling_FindReferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) RenameSymbol(ctx context.Context, in *RenameSymbolRequest, opts ...grpc.CallOption) (*RenameSymbolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameSymbolResponse)
	err := c.cc.Invoke(ctx, Tooling_RenameSymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) GetHoverInfo(ctx context.Context, in *GetHoverInfoRequest, opts ...grpc.CallOption) (*GetHoverInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHoverInfoResponse)
	err := c.cc.Invoke(ctx, Tooling_GetHoverInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) GetCompletions(ctx context.Context, in *GetCompletionsRequest, opts ...grpc.CallOption) (*GetCompletionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompletionsResponse)
	err := c.cc.Invoke(ctx, Tooling_GetCompletions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) Fix(ctx context.Context, in *FixRequest, opts ...grpc.CallOption) (*FixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FixResponse)
	err := c.cc.Invoke(ctx, Tooling_Fix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) ApplyEdit(ctx context.Context, in *ApplyEditRequest, opts ...grpc.CallOption) (*ApplyEditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyEditResponse)
	err := c.cc.Invoke(ctx, Tooling_ApplyEdit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) ListDependencies(ctx context.Context, in *ListDependenciesRequest, opts ...grpc.CallOption) (*ListDependenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDependenciesResponse)
	err := c.cc.Invoke(ctx, Tooling_ListDependencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) AddDependency(ctx context.Context, in *AddDependencyRequest, opts ...grpc.CallOption) (*AddDependencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDependencyResponse)
	err := c.cc.Invoke(ctx, Tooling_AddDependency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) RemoveDependency(ctx context.Context, in *RemoveDependencyRequest, opts ...grpc.CallOption) (*RemoveDependencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveDependencyResponse)
	err := c.cc.Invoke(ctx, Tooling_RemoveDependency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) GetProjectInfo(ctx context.Context, in *GetProjectInfoRequest, opts ...grpc.CallOption) (*GetProjectInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectInfoResponse)
	err := c.cc.Invoke(ctx, Tooling_GetProjectInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) GetCallGraph(ctx context.Context, in *GetCallGraphRequest, opts ...grpc.CallOption) (*GetCallGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCallGraphResponse)
	err := c.cc.Invoke(ctx, Tooling_GetCallGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, Tooling_Build_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, Tooling_Test_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingClient) Lint(ctx context.Context, in *LintRequest, opts ...grpc.CallOption) (*LintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LintResponse)
	err := c.cc.Invoke(ctx, Tooling_Lint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolingServer is the server API for Tooling service.
// All implementations must embed UnimplementedToolingServer
// for forward compatibility.
//
// Tooling provides language-specific code operations.
// Every language agent (go-grpc, python-fastapi, etc.) implements this service.
//
// NOTE: File operations (read, write, list, search) and git operations are
// NOT part of this service. Mind handles those directly via its VFS.
type ToolingServer interface {
	// LSP operations
	ListSymbols(context.Context, *ListSymbolsRequest) (*ListSymbolsResponse, error)
	// GetDiagnostics returns compiler, linter, or language-server diagnostics.
	GetDiagnostics(context.Context, *GetDiagnosticsRequest) (*GetDiagnosticsResponse, error)
	// GoToDefinition resolves the declaration for a symbol at a source position.
	GoToDefinition(context.Context, *GoToDefinitionRequest) (*GoToDefinitionResponse, error)
	// FindReferences resolves usage locations for a symbol at a source position.
	FindReferences(context.Context, *FindReferencesRequest) (*FindReferencesResponse, error)
	// RenameSymbol applies a language-aware rename across the service.
	RenameSymbol(context.Context, *RenameSymbolRequest) (*RenameSymbolResponse, error)
	// GetHoverInfo returns hover documentation and type information.
	GetHoverInfo(context.Context, *GetHoverInfoRequest) (*GetHoverInfoResponse, error)
	// GetCompletions returns completion suggestions at a source position.
	GetCompletions(context.Context, *GetCompletionsRequest) (*GetCompletionsResponse, error)
	// Code modification
	Fix(context.Context, *FixRequest) (*FixResponse, error)
	// ApplyEdit applies a smart edit and optional language fixers.
	ApplyEdit(context.Context, *ApplyEditRequest) (*ApplyEditResponse, error)
	// Dependency management
	ListDependencies(context.Context, *ListDependenciesRequest) (*ListDependenciesResponse, error)
	// AddDependency installs a package through the native package manager.
	AddDependency(context.Context, *AddDependencyRequest) (*AddDependencyResponse, error)
	// RemoveDependency removes a package through the native package manager.
	RemoveDependency(context.Context, *RemoveDependencyRequest) (*RemoveDependencyResponse, error)
	// Analysis
	GetProjectInfo(context.Context, *GetProjectInfoRequest) (*GetProjectInfoResponse, error)
	// GetCallGraph runs whole-program call graph analysis.
	GetCallGraph(context.Context, *GetCallGraphRequest) (*GetCallGraphResponse, error)
	// Dev validation
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
	// Test runs native tests and returns structured counts.
	Test(context.Context, *TestRequest) (*TestResponse, error)
	// Lint runs native linting and returns structured diagnostics.
	Lint(context.Context, *LintRequest) (*LintResponse, error)
	mustEmbedUnimplementedToolingServer()
}

// UnimplementedToolingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolingServer struct{}

func (UnimplementedToolingServer) ListSymbols(context.Context, *ListSymbolsRequest) (*ListSymbolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSymbols not implemented")
}
func (UnimplementedToolingServer) GetDiagnostics(context.Context, *GetDiagnosticsRequest) (*GetDiagnosticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiagnostics not implemented")
}
func (UnimplementedToolingServer) GoToDefinition(context.Context, *GoToDefinitionRequest) (*GoToDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GoToDefinition not implemented")
}
func (UnimplementedToolingServer) FindReferences(context.Context, *FindReferencesRequest) (*FindReferencesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindReferences not implemented")
}
func (UnimplementedToolingServer) RenameSymbol(context.Context, *RenameSymbolRequest) (*RenameSymbolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameSymbol not implemented")
}
func (UnimplementedToolingServer) GetHoverInfo(context.Context, *GetHoverInfoRequest) (*GetHoverInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHoverInfo not implemented")
}
func (UnimplementedToolingServer) GetCompletions(context.Context, *GetCompletionsRequest) (*GetCompletionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompletions not implemented")
}
func (UnimplementedToolingServer) Fix(context.Context, *FixRequest) (*FixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fix not implemented")
}
func (UnimplementedToolingServer) ApplyEdit(context.Context, *ApplyEditRequest) (*ApplyEditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyEdit not implemented")
}
func (UnimplementedToolingServer) ListDependencies(context.Context, *ListDependenciesRequest) (*ListDependenciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDependencies not implemented")
}
func (UnimplementedToolingServer) AddDependency(context.Context, *AddDependencyRequest) (*AddDependencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDependency not implemented")
}
func (UnimplementedToolingServer) RemoveDependency(context.Context, *RemoveDependencyRequest) (*RemoveDependencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDependency not implemented")
}
func (UnimplementedToolingServer) GetProjectInfo(context.Context, *GetProjectInfoRequest) (*GetProjectInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectInfo not implemented")
}
func (UnimplementedToolingServer) GetCallGraph(context.Context, *GetCallGraphRequest) (*GetCallGraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCallGraph not implemented")
}
func (UnimplementedToolingServer) Build(context.Context, *BuildRequest) (*BuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedToolingServer) Test(context.Context, *TestRequest) (*TestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedToolingServer) Lint(context.Context, *LintRequest) (*LintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Lint not implemented")
}
func (UnimplementedToolingServer) mustEmbedUnimplementedToolingServer() {}
func (UnimplementedToolingServer) testEmbeddedByValue()                 {}

// UnsafeToolingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolingServer will
// result in compilation errors.
type UnsafeToolingServer interface {
	mustEmbedUnimplementedToolingServer()
}

func RegisterToolingServer(s grpc.ServiceRegistrar, srv ToolingServer) {
	// If the following call panics, it indicates UnimplementedToolingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tooling_ServiceDesc, srv)
}

func _Tooling_ListSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSymbolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).ListSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_ListSymbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).ListSymbols(ctx, req.(*ListSymbolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_GetDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).GetDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_GetDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).GetDiagnostics(ctx, req.(*GetDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_GoToDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoToDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).GoToDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_GoToDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).GoToDefinition(ctx, req.(*GoToDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_FindReferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindReferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).FindReferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_FindReferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).FindReferences(ctx, req.(*FindReferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_RenameSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).RenameSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_RenameSymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).RenameSymbol(ctx, req.(*RenameSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_GetHoverInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHoverInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).GetHoverInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_GetHoverInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).GetHoverInfo(ctx, req.(*GetHoverInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_GetCompletions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompletionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).GetCompletions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_GetCompletions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).GetCompletions(ctx, req.(*GetCompletionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_Fix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).Fix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_Fix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).Fix(ctx, req.(*FixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_ApplyEdit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyEditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).ApplyEdit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_ApplyEdit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).ApplyEdit(ctx, req.(*ApplyEditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_ListDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDependenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).ListDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_ListDependencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).ListDependencies(ctx, req.(*ListDependenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_AddDependency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).AddDependency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_AddDependency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).AddDependency(ctx, req.(*AddDependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_RemoveDependency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).RemoveDependency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_RemoveDependency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).RemoveDependency(ctx, req.(*RemoveDependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_GetProjectInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).GetProjectInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_GetProjectInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).GetProjectInfo(ctx, req.(*GetProjectInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_GetCallGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCallGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).GetCallGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_GetCallGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).GetCallGraph(ctx, req.(*GetCallGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_Build_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_Test_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).Test(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tooling_Lint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServer).Lint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tooling_Lint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServer).Lint(ctx, req.(*LintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tooling_ServiceDesc is the grpc.ServiceDesc for Tooling service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tooling_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codefly.services.tooling.v0.Tooling",
	HandlerType: (*ToolingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSymbols",
			Handler:    _Tooling_ListSymbols_Handler,
		},
		{
			MethodName: "GetDiagnostics",
			Handler:    _Tooling_GetDiagnostics_Handler,
		},
		{
			MethodName: "GoToDefinition",
			Handler:    _Tooling_GoToDefinition_Handler,
		},
		{
			MethodName: "FindReferences",
			Handler:    _Tooling_FindReferences_Handler,
		},
		{
			MethodName: "RenameSymbol",
			Handler:    _Tooling_RenameSymbol_Handler,
		},
		{
			MethodName: "GetHoverInfo",
			Handler:    _Tooling_GetHoverInfo_Handler,
		},
		{
			MethodName: "GetCompletions",
			Handler:    _Tooling_GetCompletions_Handler,
		},
		{
			MethodName: "Fix",
			Handler:    _Tooling_Fix_Handler,
		},
		{
			MethodName: "ApplyEdit",
			Handler:    _Tooling_ApplyEdit_Handler,
		},
		{
			MethodName: "ListDependencies",
			Handler:    _Tooling_ListDependencies_Handler,
		},
		{
			MethodName: "AddDependency",
			Handler:    _Tooling_AddDependency_Handler,
		},
		{
			MethodName: "RemoveDependency",
			Handler:    _Tooling_RemoveDependency_Handler,
		},
		{
			MethodName: "GetProjectInfo",
			Handler:    _Tooling_GetProjectInfo_Handler,
		},
		{
			MethodName: "GetCallGraph",
			Handler:    _Tooling_GetCallGraph_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _Tooling_Build_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _Tooling_Test_Handler,
		},
		{
			MethodName: "Lint",
			Handler:    _Tooling_Lint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "codefly/services/tooling/v0/tooling.proto",
}
