// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: codefly/services/agent/v0/agent.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type enumerates implementation languages an agent can generate or analyze.
type Language_Type int32

const (
	// GO is the Go language.
	Language_GO Language_Type = 0
	// PYTHON is the Python language.
	Language_PYTHON Language_Type = 1
	// JAVASCRIPT is the JavaScript language.
	Language_JAVASCRIPT Language_Type = 2
	// TYPESCRIPT is the TypeScript language.
	Language_TYPESCRIPT Language_Type = 3
	// RUBY is the Ruby language.
	Language_RUBY Language_Type = 4
)

// Enum value maps for Language_Type.
var (
	Language_Type_name = map[int32]string{
		0: "GO",
		1: "PYTHON",
		2: "JAVASCRIPT",
		3: "TYPESCRIPT",
		4: "RUBY",
	}
	Language_Type_value = map[string]int32{
		"GO":         0,
		"PYTHON":     1,
		"JAVASCRIPT": 2,
		"TYPESCRIPT": 3,
		"RUBY":       4,
	}
)

func (x Language_Type) Enum() *Language_Type {
	p := new(Language_Type)
	*p = x
	return p
}

func (x Language_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_codefly_services_agent_v0_agent_proto_enumTypes[0].Descriptor()
}

func (Language_Type) Type() protoreflect.EnumType {
	return &file_codefly_services_agent_v0_agent_proto_enumTypes[0]
}

func (x Language_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language_Type.Descriptor instead.
func (Language_Type) EnumDescriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{0, 0}
}

// Type enumerates endpoint protocols an agent can expose.
type Protocol_Type int32

const (
	// HTTP is a generic HTTP endpoint.
	Protocol_HTTP Protocol_Type = 0
	// GRPC is a gRPC endpoint.
	Protocol_GRPC Protocol_Type = 1
)

// Enum value maps for Protocol_Type.
var (
	Protocol_Type_name = map[int32]string{
		0: "HTTP",
		1: "GRPC",
	}
	Protocol_Type_value = map[string]int32{
		"HTTP": 0,
		"GRPC": 1,
	}
)

func (x Protocol_Type) Enum() *Protocol_Type {
	p := new(Protocol_Type)
	*p = x
	return p
}

func (x Protocol_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_codefly_services_agent_v0_agent_proto_enumTypes[1].Descriptor()
}

func (Protocol_Type) Type() protoreflect.EnumType {
	return &file_codefly_services_agent_v0_agent_proto_enumTypes[1]
}

func (x Protocol_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol_Type.Descriptor instead.
func (Protocol_Type) EnumDescriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{1, 0}
}

// Type enumerates agent capabilities advertised to the CLI.
type Capability_Type int32

const (
	// UNKNOWN is the default value when type is not specified.
	Capability_UNKNOWN Capability_Type = 0
	// BUILDER means the agent implements the Builder service.
	Capability_BUILDER Capability_Type = 1
	// RUNTIME means the agent implements the Runtime service.
	Capability_RUNTIME Capability_Type = 2
	// Hot Reload is a runtime where a running process will NOT be restarted
	Capability_HOT_RELOAD Capability_Type = 3
)

// Enum value maps for Capability_Type.
var (
	Capability_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "BUILDER",
		2: "RUNTIME",
		3: "HOT_RELOAD",
	}
	Capability_Type_value = map[string]int32{
		"UNKNOWN":    0,
		"BUILDER":    1,
		"RUNTIME":    2,
		"HOT_RELOAD": 3,
	}
)

func (x Capability_Type) Enum() *Capability_Type {
	p := new(Capability_Type)
	*p = x
	return p
}

func (x Capability_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_codefly_services_agent_v0_agent_proto_enumTypes[2].Descriptor()
}

func (Capability_Type) Type() protoreflect.EnumType {
	return &file_codefly_services_agent_v0_agent_proto_enumTypes[2]
}

func (x Capability_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability_Type.Descriptor instead.
func (Capability_Type) EnumDescriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{2, 0}
}

// Type enumerates runtime toolchains agents may require.
type Runtime_Type int32

const (
	// UNKNOWN is the default value when type is not specified.
	Runtime_UNKNOWN Runtime_Type = 0
	// GO is the Go toolchain.
	Runtime_GO Runtime_Type = 1
	// NPM is the Node/npm toolchain.
	Runtime_NPM Runtime_Type = 2
	// PYTHON is the Python interpreter/toolchain.
	Runtime_PYTHON Runtime_Type = 3
	// PYTHON_POETRY is the Python Poetry toolchain.
	Runtime_PYTHON_POETRY Runtime_Type = 4
	// RUBY is the Ruby interpreter/toolchain.
	Runtime_RUBY Runtime_Type = 5
	// RUBY_GEM is the RubyGems toolchain.
	Runtime_RUBY_GEM Runtime_Type = 6
	// RUBY_BUNDLE is the Bundler toolchain.
	Runtime_RUBY_BUNDLE Runtime_Type = 7
	// NIX is the Nix runtime/toolchain.
	Runtime_NIX Runtime_Type = 8
)

// Enum value maps for Runtime_Type.
var (
	Runtime_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "GO",
		2: "NPM",
		3: "PYTHON",
		4: "PYTHON_POETRY",
		5: "RUBY",
		6: "RUBY_GEM",
		7: "RUBY_BUNDLE",
		8: "NIX",
	}
	Runtime_Type_value = map[string]int32{
		"UNKNOWN":       0,
		"GO":            1,
		"NPM":           2,
		"PYTHON":        3,
		"PYTHON_POETRY": 4,
		"RUBY":          5,
		"RUBY_GEM":      6,
		"RUBY_BUNDLE":   7,
		"NIX":           8,
	}
)

func (x Runtime_Type) Enum() *Runtime_Type {
	p := new(Runtime_Type)
	*p = x
	return p
}

func (x Runtime_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Runtime_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_codefly_services_agent_v0_agent_proto_enumTypes[3].Descriptor()
}

func (Runtime_Type) Type() protoreflect.EnumType {
	return &file_codefly_services_agent_v0_agent_proto_enumTypes[3]
}

func (x Runtime_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Runtime_Type.Descriptor instead.
func (Runtime_Type) EnumDescriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{3, 0}
}

// Language identifies an implementation language supported by an agent.
type Language struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the language represented by this entry.
	Type          Language_Type `protobuf:"varint,1,opt,name=type,proto3,enum=codefly.services.agent.v0.Language_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Language) Reset() {
	*x = Language{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Language) GetType() Language_Type {
	if x != nil {
		return x.Type
	}
	return Language_GO
}

// Protocol identifies an API protocol supported by an agent.
type Protocol struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the protocol represented by this entry.
	Type          Protocol_Type `protobuf:"varint,1,opt,name=type,proto3,enum=codefly.services.agent.v0.Protocol_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Protocol) Reset() {
	*x = Protocol{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Protocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Protocol) ProtoMessage() {}

func (x *Protocol) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Protocol.ProtoReflect.Descriptor instead.
func (*Protocol) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Protocol) GetType() Protocol_Type {
	if x != nil {
		return x.Type
	}
	return Protocol_HTTP
}

// Capability identifies one agent interface or lifecycle feature.
type Capability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the advertised capability.
	Type          Capability_Type `protobuf:"varint,1,opt,name=type,proto3,enum=codefly.services.agent.v0.Capability_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Capability) GetType() Capability_Type {
	if x != nil {
		return x.Type
	}
	return Capability_UNKNOWN
}

// Runtime describes a toolchain/runtime required by an agent.
type Runtime struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the required runtime toolchain.
	Type Runtime_Type `protobuf:"varint,1,opt,name=type,proto3,enum=codefly.services.agent.v0.Runtime_Type" json:"type,omitempty"`
	// version is the semantic or service-specific version for this resource.
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runtime) Reset() {
	*x = Runtime{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runtime) ProtoMessage() {}

func (x *Runtime) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runtime.ProtoReflect.Descriptor instead.
func (*Runtime) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Runtime) GetType() Runtime_Type {
	if x != nil {
		return x.Type
	}
	return Runtime_UNKNOWN
}

func (x *Runtime) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ConfigurationValueInformation documents one configuration field accepted by an agent.
type ConfigurationValueInformation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the configuration field name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description explains how to fill this configuration field.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationValueInformation) Reset() {
	*x = ConfigurationValueInformation{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationValueInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationValueInformation) ProtoMessage() {}

func (x *ConfigurationValueInformation) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationValueInformation.ProtoReflect.Descriptor instead.
func (*ConfigurationValueInformation) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigurationValueInformation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigurationValueInformation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ConfigurationValueDetail groups related configuration fields for an agent.
type ConfigurationValueDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the configuration detail group name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description explains the configuration group shown in generated docs.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// fields are agent-specific structured settings from service YAML.
	Fields        []*ConfigurationValueInformation `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationValueDetail) Reset() {
	*x = ConfigurationValueDetail{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationValueDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationValueDetail) ProtoMessage() {}

func (x *ConfigurationValueDetail) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationValueDetail.ProtoReflect.Descriptor instead.
func (*ConfigurationValueDetail) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigurationValueDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigurationValueDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigurationValueDetail) GetFields() []*ConfigurationValueInformation {
	if x != nil {
		return x.Fields
	}
	return nil
}

// AgentTechnique documents an agent-supported workflow or prompt technique.
type AgentTechnique struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the stable identifier for this record.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the technique display name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// description explains when the technique should be used.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// tags are labels used for filtering, grouping, or display.
	Tags []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	// prompt is the reusable instruction text for this technique.
	Prompt        string `protobuf:"bytes,5,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTechnique) Reset() {
	*x = AgentTechnique{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTechnique) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTechnique) ProtoMessage() {}

func (x *AgentTechnique) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTechnique.ProtoReflect.Descriptor instead.
func (*AgentTechnique) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentTechnique) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentTechnique) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentTechnique) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentTechnique) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AgentTechnique) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// AgentInformation is the manifest and documentation surface returned by an agent.
type AgentInformation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// runtime_requirements are toolchains the user must have available.
	RuntimeRequirements []*Runtime `protobuf:"bytes,1,rep,name=runtime_requirements,json=runtimeRequirements,proto3" json:"runtime_requirements,omitempty"`
	// capabilities describes which optional protocol features are supported.
	Capabilities []*Capability `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// protocols are endpoint protocols the agent can expose.
	Protocols []*Protocol `protobuf:"bytes,3,rep,name=protocols,proto3" json:"protocols,omitempty"`
	// languages are source languages the agent can create, run, or analyze.
	Languages []*Language `protobuf:"bytes,4,rep,name=languages,proto3" json:"languages,omitempty"`
	// read_me is the agent README or equivalent human-facing documentation.
	ReadMe string `protobuf:"bytes,5,opt,name=read_me,json=readMe,proto3" json:"read_me,omitempty"`
	// configuration_details documents service YAML fields understood by the agent.
	ConfigurationDetails []*ConfigurationValueDetail `protobuf:"bytes,6,rep,name=configuration_details,json=configurationDetails,proto3" json:"configuration_details,omitempty"`
	// techniques are reusable workflows or prompts the agent can apply.
	Techniques    []*AgentTechnique `protobuf:"bytes,7,rep,name=techniques,proto3" json:"techniques,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInformation) Reset() {
	*x = AgentInformation{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInformation) ProtoMessage() {}

func (x *AgentInformation) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInformation.ProtoReflect.Descriptor instead.
func (*AgentInformation) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AgentInformation) GetRuntimeRequirements() []*Runtime {
	if x != nil {
		return x.RuntimeRequirements
	}
	return nil
}

func (x *AgentInformation) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentInformation) GetProtocols() []*Protocol {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *AgentInformation) GetLanguages() []*Language {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *AgentInformation) GetReadMe() string {
	if x != nil {
		return x.ReadMe
	}
	return ""
}

func (x *AgentInformation) GetConfigurationDetails() []*ConfigurationValueDetail {
	if x != nil {
		return x.ConfigurationDetails
	}
	return nil
}

func (x *AgentInformation) GetTechniques() []*AgentTechnique {
	if x != nil {
		return x.Techniques
	}
	return nil
}

// AgentInformationRequest asks an agent to describe its capabilities and settings.
type AgentInformationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInformationRequest) Reset() {
	*x = AgentInformationRequest{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInformationRequest) ProtoMessage() {}

func (x *AgentInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInformationRequest.ProtoReflect.Descriptor instead.
func (*AgentInformationRequest) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{8}
}

// CommandDefinition describes a command that a plugin agent provides.
// Commands are registered at startup and routed through the Gateway.
type CommandDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the command name exposed by the plugin.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // e.g. "reset_db", "deploy", "migrate"
	// description tells users and agents when to run this command.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // "Reset the database to a clean state"
	// usage is the command-line shape shown to users and agents.
	Usage string `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"` // "! reset_db [--seed]"
	// aliases are alternate command names accepted by the plugin.
	Aliases []string `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"` // ["reset-db", "db-reset"]
	// tags are labels used for filtering, grouping, or display.
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"` // ["database", "destructive"]
	// plugin identifies the plugin that provides this command; empty means built-in.
	Plugin string `protobuf:"bytes,6,opt,name=plugin,proto3" json:"plugin,omitempty"` // which plugin provides this command
	// destructive is true when the operation can mutate or delete user state.
	Destructive bool `protobuf:"varint,7,opt,name=destructive,proto3" json:"destructive,omitempty"` // if true, requires confirmation before execution
	// needs_gateway is true when the command must call through the Mind gateway.
	NeedsGateway  bool `protobuf:"varint,8,opt,name=needs_gateway,json=needsGateway,proto3" json:"needs_gateway,omitempty"` // if true, requires a gateway connection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDefinition) Reset() {
	*x = CommandDefinition{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDefinition) ProtoMessage() {}

func (x *CommandDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDefinition.ProtoReflect.Descriptor instead.
func (*CommandDefinition) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{9}
}

func (x *CommandDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CommandDefinition) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *CommandDefinition) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *CommandDefinition) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CommandDefinition) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *CommandDefinition) GetDestructive() bool {
	if x != nil {
		return x.Destructive
	}
	return false
}

func (x *CommandDefinition) GetNeedsGateway() bool {
	if x != nil {
		return x.NeedsGateway
	}
	return false
}

// ListCommandsRequest carries optional filters for listing commands.
type ListCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandsRequest) Reset() {
	*x = ListCommandsRequest{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsRequest) ProtoMessage() {}

func (x *ListCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsRequest.ProtoReflect.Descriptor instead.
func (*ListCommandsRequest) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{10}
}

// ListCommandsResponse returns plugin and built-in commands available to callers.
type ListCommandsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// commands are plugin or built-in commands available to callers.
	Commands      []*CommandDefinition `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandsResponse) Reset() {
	*x = ListCommandsResponse{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsResponse) ProtoMessage() {}

func (x *ListCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsResponse.ProtoReflect.Descriptor instead.
func (*ListCommandsResponse) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ListCommandsResponse) GetCommands() []*CommandDefinition {
	if x != nil {
		return x.Commands
	}
	return nil
}

// RunPluginCommandRequest invokes one plugin-provided command by name.
type RunPluginCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command is the plugin command name to run.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// args are command arguments passed to the plugin command handler.
	Args          []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPluginCommandRequest) Reset() {
	*x = RunPluginCommandRequest{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPluginCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPluginCommandRequest) ProtoMessage() {}

func (x *RunPluginCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPluginCommandRequest.ProtoReflect.Descriptor instead.
func (*RunPluginCommandRequest) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{12}
}

func (x *RunPluginCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunPluginCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// RunPluginCommandResponse reports command output and command-level failure details.
type RunPluginCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success is true when the requested operation completed successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// output is raw command, build, lint, or test output preserved for diagnostics.
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// error explains why the operation failed; empty means success at this layer.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPluginCommandResponse) Reset() {
	*x = RunPluginCommandResponse{}
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPluginCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPluginCommandResponse) ProtoMessage() {}

func (x *RunPluginCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPluginCommandResponse.ProtoReflect.Descriptor instead.
func (*RunPluginCommandResponse) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_agent_proto_rawDescGZIP(), []int{13}
}

func (x *RunPluginCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RunPluginCommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RunPluginCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_codefly_services_agent_v0_agent_proto protoreflect.FileDescriptor

const file_codefly_services_agent_v0_agent_proto_rawDesc = "" +
	"\n" +
	"%codefly/services/agent/v0/agent.proto\x12\x19codefly.services.agent.v0\"\x8e\x01\n" +
	"\bLanguage\x12<\n" +
	"\x04type\x18\x01 \x01(\x0e2(.codefly.services.agent.v0.Language.TypeR\x04type\"D\n" +
	"\x04Type\x12\x06\n" +
	"\x02GO\x10\x00\x12\n" +
	"\n" +
	"\x06PYTHON\x10\x01\x12\x0e\n" +
	"\n" +
	"JAVASCRIPT\x10\x02\x12\x0e\n" +
	"\n" +
	"TYPESCRIPT\x10\x03\x12\b\n" +
	"\x04RUBY\x10\x04\"d\n" +
	"\bProtocol\x12<\n" +
	"\x04type\x18\x01 \x01(\x0e2(.codefly.services.agent.v0.Protocol.TypeR\x04type\"\x1a\n" +
	"\x04Type\x12\b\n" +
	"\x04HTTP\x10\x00\x12\b\n" +
	"\x04GRPC\x10\x01\"\x8b\x01\n" +
	"\n" +
	"Capability\x12>\n" +
	"\x04type\x18\x01 \x01(\x0e2*.codefly.services.agent.v0.Capability.TypeR\x04type\"=\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aBUILDER\x10\x01\x12\v\n" +
	"\aRUNTIME\x10\x02\x12\x0e\n" +
	"\n" +
	"HOT_RELOAD\x10\x03\"\xd7\x01\n" +
	"\aRuntime\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.codefly.services.agent.v0.Runtime.TypeR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"u\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x06\n" +
	"\x02GO\x10\x01\x12\a\n" +
	"\x03NPM\x10\x02\x12\n" +
	"\n" +
	"\x06PYTHON\x10\x03\x12\x11\n" +
	"\rPYTHON_POETRY\x10\x04\x12\b\n" +
	"\x04RUBY\x10\x05\x12\f\n" +
	"\bRUBY_GEM\x10\x06\x12\x0f\n" +
	"\vRUBY_BUNDLE\x10\a\x12\a\n" +
	"\x03NIX\x10\b\"U\n" +
	"\x1dConfigurationValueInformation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xa2\x01\n" +
	"\x18ConfigurationValueDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12P\n" +
	"\x06fields\x18\x03 \x03(\v28.codefly.services.agent.v0.ConfigurationValueInformationR\x06fields\"\x82\x01\n" +
	"\x0eAgentTechnique\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x16\n" +
	"\x06prompt\x18\x05 \x01(\tR\x06prompt\"\x88\x04\n" +
	"\x10AgentInformation\x12U\n" +
	"\x14runtime_requirements\x18\x01 \x03(\v2\".codefly.services.agent.v0.RuntimeR\x13runtimeRequirements\x12I\n" +
	"\fcapabilities\x18\x02 \x03(\v2%.codefly.services.agent.v0.CapabilityR\fcapabilities\x12A\n" +
	"\tprotocols\x18\x03 \x03(\v2#.codefly.services.agent.v0.ProtocolR\tprotocols\x12A\n" +
	"\tlanguages\x18\x04 \x03(\v2#.codefly.services.agent.v0.LanguageR\tlanguages\x12\x17\n" +
	"\aread_me\x18\x05 \x01(\tR\x06readMe\x12h\n" +
	"\x15configuration_details\x18\x06 \x03(\v23.codefly.services.agent.v0.ConfigurationValueDetailR\x14configurationDetails\x12I\n" +
	"\n" +
	"techniques\x18\a \x03(\v2).codefly.services.agent.v0.AgentTechniqueR\n" +
	"techniques\"\x19\n" +
	"\x17AgentInformationRequest\"\xec\x01\n" +
	"\x11CommandDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05usage\x18\x03 \x01(\tR\x05usage\x12\x18\n" +
	"\aaliases\x18\x04 \x03(\tR\aaliases\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06plugin\x18\x06 \x01(\tR\x06plugin\x12 \n" +
	"\vdestructive\x18\a \x01(\bR\vdestructive\x12#\n" +
	"\rneeds_gateway\x18\b \x01(\bR\fneedsGateway\"\x15\n" +
	"\x13ListCommandsRequest\"`\n" +
	"\x14ListCommandsResponse\x12H\n" +
	"\bcommands\x18\x01 \x03(\v2,.codefly.services.agent.v0.CommandDefinitionR\bcommands\"G\n" +
	"\x17RunPluginCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"b\n" +
	"\x18RunPluginCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xf3\x02\n" +
	"\x05Agent\x12x\n" +
	"\x13GetAgentInformation\x122.codefly.services.agent.v0.AgentInformationRequest\x1a+.codefly.services.agent.v0.AgentInformation\"\x00\x12q\n" +
	"\fListCommands\x12..codefly.services.agent.v0.ListCommandsRequest\x1a/.codefly.services.agent.v0.ListCommandsResponse\"\x00\x12}\n" +
	"\x10RunPluginCommand\x122.codefly.services.agent.v0.RunPluginCommandRequest\x1a3.codefly.services.agent.v0.RunPluginCommandResponse\"\x00B\xf7\x01\n" +
	"\x1dcom.codefly.services.agent.v0B\n" +
	"AgentProtoP\x01ZBgithub.com/codefly-dev/core/generated/go/codefly/services/agent/v0\xa2\x02\x04CSAV\xaa\x02\x19Codefly.Services.Agent.V0\xca\x02\x19Codefly\\Services\\Agent\\V0\xe2\x02%Codefly\\Services\\Agent\\V0\\GPBMetadata\xea\x02\x1cCodefly::Services::Agent::V0b\x06proto3"

var (
	file_codefly_services_agent_v0_agent_proto_rawDescOnce sync.Once
	file_codefly_services_agent_v0_agent_proto_rawDescData []byte
)

func file_codefly_services_agent_v0_agent_proto_rawDescGZIP() []byte {
	file_codefly_services_agent_v0_agent_proto_rawDescOnce.Do(func() {
		file_codefly_services_agent_v0_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codefly_services_agent_v0_agent_proto_rawDesc), len(file_codefly_services_agent_v0_agent_proto_rawDesc)))
	})
	return file_codefly_services_agent_v0_agent_proto_rawDescData
}

var file_codefly_services_agent_v0_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_codefly_services_agent_v0_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_codefly_services_agent_v0_agent_proto_goTypes = []any{
	(Language_Type)(0),                    // 0: codefly.services.agent.v0.Language.Type
	(Protocol_Type)(0),                    // 1: codefly.services.agent.v0.Protocol.Type
	(Capability_Type)(0),                  // 2: codefly.services.agent.v0.Capability.Type
	(Runtime_Type)(0),                     // 3: codefly.services.agent.v0.Runtime.Type
	(*Language)(nil),                      // 4: codefly.services.agent.v0.Language
	(*Protocol)(nil),                      // 5: codefly.services.agent.v0.Protocol
	(*Capability)(nil),                    // 6: codefly.services.agent.v0.Capability
	(*Runtime)(nil),                       // 7: codefly.services.agent.v0.Runtime
	(*ConfigurationValueInformation)(nil), // 8: codefly.services.agent.v0.ConfigurationValueInformation
	(*ConfigurationValueDetail)(nil),      // 9: codefly.services.agent.v0.ConfigurationValueDetail
	(*AgentTechnique)(nil),                // 10: codefly.services.agent.v0.AgentTechnique
	(*AgentInformation)(nil),              // 11: codefly.services.agent.v0.AgentInformation
	(*AgentInformationRequest)(nil),       // 12: codefly.services.agent.v0.AgentInformationRequest
	(*CommandDefinition)(nil),             // 13: codefly.services.agent.v0.CommandDefinition
	(*ListCommandsRequest)(nil),           // 14: codefly.services.agent.v0.ListCommandsRequest
	(*ListCommandsResponse)(nil),          // 15: codefly.services.agent.v0.ListCommandsResponse
	(*RunPluginCommandRequest)(nil),       // 16: codefly.services.agent.v0.RunPluginCommandRequest
	(*RunPluginCommandResponse)(nil),      // 17: codefly.services.agent.v0.RunPluginCommandResponse
}
var file_codefly_services_agent_v0_agent_proto_depIdxs = []int32{
	0,  // 0: codefly.services.agent.v0.Language.type:type_name -> codefly.services.agent.v0.Language.Type
	1,  // 1: codefly.services.agent.v0.Protocol.type:type_name -> codefly.services.agent.v0.Protocol.Type
	2,  // 2: codefly.services.agent.v0.Capability.type:type_name -> codefly.services.agent.v0.Capability.Type
	3,  // 3: codefly.services.agent.v0.Runtime.type:type_name -> codefly.services.agent.v0.Runtime.Type
	8,  // 4: codefly.services.agent.v0.ConfigurationValueDetail.fields:type_name -> codefly.services.agent.v0.ConfigurationValueInformation
	7,  // 5: codefly.services.agent.v0.AgentInformation.runtime_requirements:type_name -> codefly.services.agent.v0.Runtime
	6,  // 6: codefly.services.agent.v0.AgentInformation.capabilities:type_name -> codefly.services.agent.v0.Capability
	5,  // 7: codefly.services.agent.v0.AgentInformation.protocols:type_name -> codefly.services.agent.v0.Protocol
	4,  // 8: codefly.services.agent.v0.AgentInformation.languages:type_name -> codefly.services.agent.v0.Language
	9,  // 9: codefly.services.agent.v0.AgentInformation.configuration_details:type_name -> codefly.services.agent.v0.ConfigurationValueDetail
	10, // 10: codefly.services.agent.v0.AgentInformation.techniques:type_name -> codefly.services.agent.v0.AgentTechnique
	13, // 11: codefly.services.agent.v0.ListCommandsResponse.commands:type_name -> codefly.services.agent.v0.CommandDefinition
	12, // 12: codefly.services.agent.v0.Agent.GetAgentInformation:input_type -> codefly.services.agent.v0.AgentInformationRequest
	14, // 13: codefly.services.agent.v0.Agent.ListCommands:input_type -> codefly.services.agent.v0.ListCommandsRequest
	16, // 14: codefly.services.agent.v0.Agent.RunPluginCommand:input_type -> codefly.services.agent.v0.RunPluginCommandRequest
	11, // 15: codefly.services.agent.v0.Agent.GetAgentInformation:output_type -> codefly.services.agent.v0.AgentInformation
	15, // 16: codefly.services.agent.v0.Agent.ListCommands:output_type -> codefly.services.agent.v0.ListCommandsResponse
	17, // 17: codefly.services.agent.v0.Agent.RunPluginCommand:output_type -> codefly.services.agent.v0.RunPluginCommandResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_codefly_services_agent_v0_agent_proto_init() }
func file_codefly_services_agent_v0_agent_proto_init() {
	if File_codefly_services_agent_v0_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codefly_services_agent_v0_agent_proto_rawDesc), len(file_codefly_services_agent_v0_agent_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_codefly_services_agent_v0_agent_proto_goTypes,
		DependencyIndexes: file_codefly_services_agent_v0_agent_proto_depIdxs,
		EnumInfos:         file_codefly_services_agent_v0_agent_proto_enumTypes,
		MessageInfos:      file_codefly_services_agent_v0_agent_proto_msgTypes,
	}.Build()
	File_codefly_services_agent_v0_agent_proto = out.File
	file_codefly_services_agent_v0_agent_proto_goTypes = nil
	file_codefly_services_agent_v0_agent_proto_depIdxs = nil
}
