// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: codefly/services/agent/v0/cyclonedx.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComponentType int32

const (
	ComponentType_LIBRARY   ComponentType = 0
	ComponentType_FRAMEWORK ComponentType = 1
	ComponentType_MODULE    ComponentType = 2
	ComponentType_CONTAINER ComponentType = 3 // Add other component types
)

// Enum value maps for ComponentType.
var (
	ComponentType_name = map[int32]string{
		0: "LIBRARY",
		1: "FRAMEWORK",
		2: "MODULE",
		3: "CONTAINER",
	}
	ComponentType_value = map[string]int32{
		"LIBRARY":   0,
		"FRAMEWORK": 1,
		"MODULE":    2,
		"CONTAINER": 3,
	}
)

func (x ComponentType) Enum() *ComponentType {
	p := new(ComponentType)
	*p = x
	return p
}

func (x ComponentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentType) Descriptor() protoreflect.EnumDescriptor {
	return file_codefly_services_agent_v0_cyclonedx_proto_enumTypes[0].Descriptor()
}

func (ComponentType) Type() protoreflect.EnumType {
	return &file_codefly_services_agent_v0_cyclonedx_proto_enumTypes[0]
}

func (x ComponentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentType.Descriptor instead.
func (ComponentType) EnumDescriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_cyclonedx_proto_rawDescGZIP(), []int{0}
}

// Represents a component in the SBOM
type Component struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Type          ComponentType          `protobuf:"varint,3,opt,name=type,proto3,enum=codefly.services.agent.v0.ComponentType" json:"type,omitempty"`
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"` // Optional
	Purl          string                 `protobuf:"bytes,5,opt,name=purl,proto3" json:"purl,omitempty"`   // Package URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_codefly_services_agent_v0_cyclonedx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_cyclonedx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_cyclonedx_proto_rawDescGZIP(), []int{0}
}

func (x *Component) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Component) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Component) GetType() ComponentType {
	if x != nil {
		return x.Type
	}
	return ComponentType_LIBRARY
}

func (x *Component) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Component) GetPurl() string {
	if x != nil {
		return x.Purl
	}
	return ""
}

// Represents the entire SBOM
type Bom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BomFormat     string                 `protobuf:"bytes,1,opt,name=bomFormat,proto3" json:"bomFormat,omitempty"` // Always "CycloneDX"
	SpecVersion   string                 `protobuf:"bytes,2,opt,name=specVersion,proto3" json:"specVersion,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,3,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Components    []*Component           `protobuf:"bytes,5,rep,name=components,proto3" json:"components,omitempty"` // Add other fields like metadata, dependencies, vulnerabilities, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bom) Reset() {
	*x = Bom{}
	mi := &file_codefly_services_agent_v0_cyclonedx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bom) ProtoMessage() {}

func (x *Bom) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_agent_v0_cyclonedx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bom.ProtoReflect.Descriptor instead.
func (*Bom) Descriptor() ([]byte, []int) {
	return file_codefly_services_agent_v0_cyclonedx_proto_rawDescGZIP(), []int{1}
}

func (x *Bom) GetBomFormat() string {
	if x != nil {
		return x.BomFormat
	}
	return ""
}

func (x *Bom) GetSpecVersion() string {
	if x != nil {
		return x.SpecVersion
	}
	return ""
}

func (x *Bom) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Bom) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Bom) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

var File_codefly_services_agent_v0_cyclonedx_proto protoreflect.FileDescriptor

const file_codefly_services_agent_v0_cyclonedx_proto_rawDesc = "" +
	"\n" +
	")codefly/services/agent/v0/cyclonedx.proto\x12\x19codefly.services.agent.v0\"\xa1\x01\n" +
	"\tComponent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12<\n" +
	"\x04type\x18\x03 \x01(\x0e2(.codefly.services.agent.v0.ComponentTypeR\x04type\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12\x12\n" +
	"\x04purl\x18\x05 \x01(\tR\x04purl\"\xc9\x01\n" +
	"\x03Bom\x12\x1c\n" +
	"\tbomFormat\x18\x01 \x01(\tR\tbomFormat\x12 \n" +
	"\vspecVersion\x18\x02 \x01(\tR\vspecVersion\x12\"\n" +
	"\fserialNumber\x18\x03 \x01(\tR\fserialNumber\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12D\n" +
	"\n" +
	"components\x18\x05 \x03(\v2$.codefly.services.agent.v0.ComponentR\n" +
	"components*F\n" +
	"\rComponentType\x12\v\n" +
	"\aLIBRARY\x10\x00\x12\r\n" +
	"\tFRAMEWORK\x10\x01\x12\n" +
	"\n" +
	"\x06MODULE\x10\x02\x12\r\n" +
	"\tCONTAINER\x10\x03B\xfb\x01\n" +
	"\x1dcom.codefly.services.agent.v0B\x0eCyclonedxProtoP\x01ZBgithub.com/codefly-dev/core/generated/go/codefly/services/agent/v0\xa2\x02\x04CSAV\xaa\x02\x19Codefly.Services.Agent.V0\xca\x02\x19Codefly\\Services\\Agent\\V0\xe2\x02%Codefly\\Services\\Agent\\V0\\GPBMetadata\xea\x02\x1cCodefly::Services::Agent::V0b\x06proto3"

var (
	file_codefly_services_agent_v0_cyclonedx_proto_rawDescOnce sync.Once
	file_codefly_services_agent_v0_cyclonedx_proto_rawDescData []byte
)

func file_codefly_services_agent_v0_cyclonedx_proto_rawDescGZIP() []byte {
	file_codefly_services_agent_v0_cyclonedx_proto_rawDescOnce.Do(func() {
		file_codefly_services_agent_v0_cyclonedx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codefly_services_agent_v0_cyclonedx_proto_rawDesc), len(file_codefly_services_agent_v0_cyclonedx_proto_rawDesc)))
	})
	return file_codefly_services_agent_v0_cyclonedx_proto_rawDescData
}

var file_codefly_services_agent_v0_cyclonedx_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_codefly_services_agent_v0_cyclonedx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_codefly_services_agent_v0_cyclonedx_proto_goTypes = []any{
	(ComponentType)(0), // 0: codefly.services.agent.v0.ComponentType
	(*Component)(nil),  // 1: codefly.services.agent.v0.Component
	(*Bom)(nil),        // 2: codefly.services.agent.v0.Bom
}
var file_codefly_services_agent_v0_cyclonedx_proto_depIdxs = []int32{
	0, // 0: codefly.services.agent.v0.Component.type:type_name -> codefly.services.agent.v0.ComponentType
	1, // 1: codefly.services.agent.v0.Bom.components:type_name -> codefly.services.agent.v0.Component
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_codefly_services_agent_v0_cyclonedx_proto_init() }
func file_codefly_services_agent_v0_cyclonedx_proto_init() {
	if File_codefly_services_agent_v0_cyclonedx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codefly_services_agent_v0_cyclonedx_proto_rawDesc), len(file_codefly_services_agent_v0_cyclonedx_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codefly_services_agent_v0_cyclonedx_proto_goTypes,
		DependencyIndexes: file_codefly_services_agent_v0_cyclonedx_proto_depIdxs,
		EnumInfos:         file_codefly_services_agent_v0_cyclonedx_proto_enumTypes,
		MessageInfos:      file_codefly_services_agent_v0_cyclonedx_proto_msgTypes,
	}.Build()
	File_codefly_services_agent_v0_cyclonedx_proto = out.File
	file_codefly_services_agent_v0_cyclonedx_proto_goTypes = nil
	file_codefly_services_agent_v0_cyclonedx_proto_depIdxs = nil
}
