// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: codefly/actions/v0/application.proto

package v0

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v0 "github.com/codefly-dev/core/generated/go/codefly/base/v0"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddApplication struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// name is the name of the application.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// description provides a brief explanation of the application.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// agent is the agent that builds/runs the application.
	Agent         *v0.Agent `protobuf:"bytes,4,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddApplication) Reset() {
	*x = AddApplication{}
	mi := &file_codefly_actions_v0_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddApplication) ProtoMessage() {}

func (x *AddApplication) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_actions_v0_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddApplication.ProtoReflect.Descriptor instead.
func (*AddApplication) Descriptor() ([]byte, []int) {
	return file_codefly_actions_v0_application_proto_rawDescGZIP(), []int{0}
}

func (x *AddApplication) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AddApplication) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddApplication) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddApplication) GetAgent() *v0.Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type AddApplicationDependency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is the type of the action.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// name is the name of the application.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// module is the name of the module that the application belongs to.
	Module string `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	// dependency_name is the name of the dependency (another application).
	DependencyName string `protobuf:"bytes,4,opt,name=dependency_name,json=dependencyName,proto3" json:"dependency_name,omitempty"`
	// dependency_module is the name of the module that the dependency belongs to.
	DependencyModule string `protobuf:"bytes,5,opt,name=dependency_module,json=dependencyModule,proto3" json:"dependency_module,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddApplicationDependency) Reset() {
	*x = AddApplicationDependency{}
	mi := &file_codefly_actions_v0_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddApplicationDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddApplicationDependency) ProtoMessage() {}

func (x *AddApplicationDependency) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_actions_v0_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddApplicationDependency.ProtoReflect.Descriptor instead.
func (*AddApplicationDependency) Descriptor() ([]byte, []int) {
	return file_codefly_actions_v0_application_proto_rawDescGZIP(), []int{1}
}

func (x *AddApplicationDependency) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AddApplicationDependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddApplicationDependency) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *AddApplicationDependency) GetDependencyName() string {
	if x != nil {
		return x.DependencyName
	}
	return ""
}

func (x *AddApplicationDependency) GetDependencyModule() string {
	if x != nil {
		return x.DependencyModule
	}
	return ""
}

var File_codefly_actions_v0_application_proto protoreflect.FileDescriptor

const file_codefly_actions_v0_application_proto_rawDesc = "" +
	"\n" +
	"$codefly/actions/v0/application.proto\x12\x12codefly.actions.v0\x1a\x1bbuf/validate/validate.proto\x1a\x1bcodefly/base/v0/agent.proto\"\x93\x01\n" +
	"\x0eAddApplication\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x182R\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12,\n" +
	"\x05agent\x18\x04 \x01(\v2\x16.codefly.base.v0.AgentR\x05agent\"\xdc\x01\n" +
	"\x18AddApplicationDependency\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x182R\x04name\x12!\n" +
	"\x06module\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x182R\x06module\x122\n" +
	"\x0fdependency_name\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x182R\x0edependencyName\x126\n" +
	"\x11dependency_module\x18\x05 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x182R\x10dependencyModuleB\xd1\x01\n" +
	"\x16com.codefly.actions.v0B\x10ApplicationProtoP\x01Z;github.com/codefly-dev/core/generated/go/codefly/actions/v0\xa2\x02\x03CAV\xaa\x02\x12Codefly.Actions.V0\xca\x02\x12Codefly\\Actions\\V0\xe2\x02\x1eCodefly\\Actions\\V0\\GPBMetadata\xea\x02\x14Codefly::Actions::V0b\x06proto3"

var (
	file_codefly_actions_v0_application_proto_rawDescOnce sync.Once
	file_codefly_actions_v0_application_proto_rawDescData []byte
)

func file_codefly_actions_v0_application_proto_rawDescGZIP() []byte {
	file_codefly_actions_v0_application_proto_rawDescOnce.Do(func() {
		file_codefly_actions_v0_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codefly_actions_v0_application_proto_rawDesc), len(file_codefly_actions_v0_application_proto_rawDesc)))
	})
	return file_codefly_actions_v0_application_proto_rawDescData
}

var file_codefly_actions_v0_application_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_codefly_actions_v0_application_proto_goTypes = []any{
	(*AddApplication)(nil),           // 0: codefly.actions.v0.AddApplication
	(*AddApplicationDependency)(nil), // 1: codefly.actions.v0.AddApplicationDependency
	(*v0.Agent)(nil),                 // 2: codefly.base.v0.Agent
}
var file_codefly_actions_v0_application_proto_depIdxs = []int32{
	2, // 0: codefly.actions.v0.AddApplication.agent:type_name -> codefly.base.v0.Agent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_codefly_actions_v0_application_proto_init() }
func file_codefly_actions_v0_application_proto_init() {
	if File_codefly_actions_v0_application_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codefly_actions_v0_application_proto_rawDesc), len(file_codefly_actions_v0_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codefly_actions_v0_application_proto_goTypes,
		DependencyIndexes: file_codefly_actions_v0_application_proto_depIdxs,
		MessageInfos:      file_codefly_actions_v0_application_proto_msgTypes,
	}.Build()
	File_codefly_actions_v0_application_proto = out.File
	file_codefly_actions_v0_application_proto_goTypes = nil
	file_codefly_actions_v0_application_proto_depIdxs = nil
}
