// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: codefly/services/builder/v0/deployment.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploymentKind int32

const (
	DeploymentKind_KUSTOMIZE DeploymentKind = 0
)

// Enum value maps for DeploymentKind.
var (
	DeploymentKind_name = map[int32]string{
		0: "KUSTOMIZE",
	}
	DeploymentKind_value = map[string]int32{
		"KUSTOMIZE": 0,
	}
)

func (x DeploymentKind) Enum() *DeploymentKind {
	p := new(DeploymentKind)
	*p = x
	return p
}

func (x DeploymentKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentKind) Descriptor() protoreflect.EnumDescriptor {
	return file_codefly_services_builder_v0_deployment_proto_enumTypes[0].Descriptor()
}

func (DeploymentKind) Type() protoreflect.EnumType {
	return &file_codefly_services_builder_v0_deployment_proto_enumTypes[0]
}

func (x DeploymentKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentKind.Descriptor instead.
func (DeploymentKind) EnumDescriptor() ([]byte, []int) {
	return file_codefly_services_builder_v0_deployment_proto_rawDescGZIP(), []int{0}
}

type KubernetesDeploymentOutput_Kind int32

const (
	KubernetesDeploymentOutput_Kustomize KubernetesDeploymentOutput_Kind = 0
)

// Enum value maps for KubernetesDeploymentOutput_Kind.
var (
	KubernetesDeploymentOutput_Kind_name = map[int32]string{
		0: "Kustomize",
	}
	KubernetesDeploymentOutput_Kind_value = map[string]int32{
		"Kustomize": 0,
	}
)

func (x KubernetesDeploymentOutput_Kind) Enum() *KubernetesDeploymentOutput_Kind {
	p := new(KubernetesDeploymentOutput_Kind)
	*p = x
	return p
}

func (x KubernetesDeploymentOutput_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KubernetesDeploymentOutput_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_codefly_services_builder_v0_deployment_proto_enumTypes[1].Descriptor()
}

func (KubernetesDeploymentOutput_Kind) Type() protoreflect.EnumType {
	return &file_codefly_services_builder_v0_deployment_proto_enumTypes[1]
}

func (x KubernetesDeploymentOutput_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KubernetesDeploymentOutput_Kind.Descriptor instead.
func (KubernetesDeploymentOutput_Kind) EnumDescriptor() ([]byte, []int) {
	return file_codefly_services_builder_v0_deployment_proto_rawDescGZIP(), []int{3, 0}
}

type Deployment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Deployment_Kubernetes
	Kind          isDeployment_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_codefly_services_builder_v0_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_builder_v0_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_codefly_services_builder_v0_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *Deployment) GetKind() isDeployment_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Deployment) GetKubernetes() *KubernetesDeployment {
	if x != nil {
		if x, ok := x.Kind.(*Deployment_Kubernetes); ok {
			return x.Kubernetes
		}
	}
	return nil
}

type isDeployment_Kind interface {
	isDeployment_Kind()
}

type Deployment_Kubernetes struct {
	Kubernetes *KubernetesDeployment `protobuf:"bytes,2,opt,name=kubernetes,proto3,oneof"`
}

func (*Deployment_Kubernetes) isDeployment_Kind() {}

type KubernetesDeployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	BuildContext  *DockerBuildContext    `protobuf:"bytes,3,opt,name=build_context,json=buildContext,proto3" json:"build_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesDeployment) Reset() {
	*x = KubernetesDeployment{}
	mi := &file_codefly_services_builder_v0_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesDeployment) ProtoMessage() {}

func (x *KubernetesDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_builder_v0_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesDeployment.ProtoReflect.Descriptor instead.
func (*KubernetesDeployment) Descriptor() ([]byte, []int) {
	return file_codefly_services_builder_v0_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *KubernetesDeployment) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubernetesDeployment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *KubernetesDeployment) GetBuildContext() *DockerBuildContext {
	if x != nil {
		return x.BuildContext
	}
	return nil
}

type DeploymentOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*DeploymentOutput_Kubernetes
	Kind          isDeploymentOutput_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentOutput) Reset() {
	*x = DeploymentOutput{}
	mi := &file_codefly_services_builder_v0_deployment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentOutput) ProtoMessage() {}

func (x *DeploymentOutput) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_builder_v0_deployment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentOutput.ProtoReflect.Descriptor instead.
func (*DeploymentOutput) Descriptor() ([]byte, []int) {
	return file_codefly_services_builder_v0_deployment_proto_rawDescGZIP(), []int{2}
}

func (x *DeploymentOutput) GetKind() isDeploymentOutput_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *DeploymentOutput) GetKubernetes() *KubernetesDeploymentOutput {
	if x != nil {
		if x, ok := x.Kind.(*DeploymentOutput_Kubernetes); ok {
			return x.Kubernetes
		}
	}
	return nil
}

type isDeploymentOutput_Kind interface {
	isDeploymentOutput_Kind()
}

type DeploymentOutput_Kubernetes struct {
	Kubernetes *KubernetesDeploymentOutput `protobuf:"bytes,2,opt,name=kubernetes,proto3,oneof"`
}

func (*DeploymentOutput_Kubernetes) isDeploymentOutput_Kind() {}

type KubernetesDeploymentOutput struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Kind          KubernetesDeploymentOutput_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=codefly.services.builder.v0.KubernetesDeploymentOutput_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesDeploymentOutput) Reset() {
	*x = KubernetesDeploymentOutput{}
	mi := &file_codefly_services_builder_v0_deployment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesDeploymentOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesDeploymentOutput) ProtoMessage() {}

func (x *KubernetesDeploymentOutput) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_services_builder_v0_deployment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesDeploymentOutput.ProtoReflect.Descriptor instead.
func (*KubernetesDeploymentOutput) Descriptor() ([]byte, []int) {
	return file_codefly_services_builder_v0_deployment_proto_rawDescGZIP(), []int{3}
}

func (x *KubernetesDeploymentOutput) GetKind() KubernetesDeploymentOutput_Kind {
	if x != nil {
		return x.Kind
	}
	return KubernetesDeploymentOutput_Kustomize
}

var File_codefly_services_builder_v0_deployment_proto protoreflect.FileDescriptor

const file_codefly_services_builder_v0_deployment_proto_rawDesc = "" +
	"\n" +
	",codefly/services/builder/v0/deployment.proto\x12\x1bcodefly.services.builder.v0\x1a(codefly/services/builder/v0/docker.proto\"i\n" +
	"\n" +
	"Deployment\x12S\n" +
	"\n" +
	"kubernetes\x18\x02 \x01(\v21.codefly.services.builder.v0.KubernetesDeploymentH\x00R\n" +
	"kubernetesB\x06\n" +
	"\x04kind\"\xac\x01\n" +
	"\x14KubernetesDeployment\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12T\n" +
	"\rbuild_context\x18\x03 \x01(\v2/.codefly.services.builder.v0.DockerBuildContextR\fbuildContext\"u\n" +
	"\x10DeploymentOutput\x12Y\n" +
	"\n" +
	"kubernetes\x18\x02 \x01(\v27.codefly.services.builder.v0.KubernetesDeploymentOutputH\x00R\n" +
	"kubernetesB\x06\n" +
	"\x04kind\"\x85\x01\n" +
	"\x1aKubernetesDeploymentOutput\x12P\n" +
	"\x04kind\x18\x01 \x01(\x0e2<.codefly.services.builder.v0.KubernetesDeploymentOutput.KindR\x04kind\"\x15\n" +
	"\x04Kind\x12\r\n" +
	"\tKustomize\x10\x00*\x1f\n" +
	"\x0eDeploymentKind\x12\r\n" +
	"\tKUSTOMIZE\x10\x00B\x88\x02\n" +
	"\x1fcom.codefly.services.builder.v0B\x0fDeploymentProtoP\x01ZDgithub.com/codefly-dev/core/generated/go/codefly/services/builder/v0\xa2\x02\x04CSBV\xaa\x02\x1bCodefly.Services.Builder.V0\xca\x02\x1bCodefly\\Services\\Builder\\V0\xe2\x02'Codefly\\Services\\Builder\\V0\\GPBMetadata\xea\x02\x1eCodefly::Services::Builder::V0b\x06proto3"

var (
	file_codefly_services_builder_v0_deployment_proto_rawDescOnce sync.Once
	file_codefly_services_builder_v0_deployment_proto_rawDescData []byte
)

func file_codefly_services_builder_v0_deployment_proto_rawDescGZIP() []byte {
	file_codefly_services_builder_v0_deployment_proto_rawDescOnce.Do(func() {
		file_codefly_services_builder_v0_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codefly_services_builder_v0_deployment_proto_rawDesc), len(file_codefly_services_builder_v0_deployment_proto_rawDesc)))
	})
	return file_codefly_services_builder_v0_deployment_proto_rawDescData
}

var file_codefly_services_builder_v0_deployment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_codefly_services_builder_v0_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_codefly_services_builder_v0_deployment_proto_goTypes = []any{
	(DeploymentKind)(0),                  // 0: codefly.services.builder.v0.DeploymentKind
	(KubernetesDeploymentOutput_Kind)(0), // 1: codefly.services.builder.v0.KubernetesDeploymentOutput.Kind
	(*Deployment)(nil),                   // 2: codefly.services.builder.v0.Deployment
	(*KubernetesDeployment)(nil),         // 3: codefly.services.builder.v0.KubernetesDeployment
	(*DeploymentOutput)(nil),             // 4: codefly.services.builder.v0.DeploymentOutput
	(*KubernetesDeploymentOutput)(nil),   // 5: codefly.services.builder.v0.KubernetesDeploymentOutput
	(*DockerBuildContext)(nil),           // 6: codefly.services.builder.v0.DockerBuildContext
}
var file_codefly_services_builder_v0_deployment_proto_depIdxs = []int32{
	3, // 0: codefly.services.builder.v0.Deployment.kubernetes:type_name -> codefly.services.builder.v0.KubernetesDeployment
	6, // 1: codefly.services.builder.v0.KubernetesDeployment.build_context:type_name -> codefly.services.builder.v0.DockerBuildContext
	5, // 2: codefly.services.builder.v0.DeploymentOutput.kubernetes:type_name -> codefly.services.builder.v0.KubernetesDeploymentOutput
	1, // 3: codefly.services.builder.v0.KubernetesDeploymentOutput.kind:type_name -> codefly.services.builder.v0.KubernetesDeploymentOutput.Kind
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_codefly_services_builder_v0_deployment_proto_init() }
func file_codefly_services_builder_v0_deployment_proto_init() {
	if File_codefly_services_builder_v0_deployment_proto != nil {
		return
	}
	file_codefly_services_builder_v0_docker_proto_init()
	file_codefly_services_builder_v0_deployment_proto_msgTypes[0].OneofWrappers = []any{
		(*Deployment_Kubernetes)(nil),
	}
	file_codefly_services_builder_v0_deployment_proto_msgTypes[2].OneofWrappers = []any{
		(*DeploymentOutput_Kubernetes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codefly_services_builder_v0_deployment_proto_rawDesc), len(file_codefly_services_builder_v0_deployment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codefly_services_builder_v0_deployment_proto_goTypes,
		DependencyIndexes: file_codefly_services_builder_v0_deployment_proto_depIdxs,
		EnumInfos:         file_codefly_services_builder_v0_deployment_proto_enumTypes,
		MessageInfos:      file_codefly_services_builder_v0_deployment_proto_msgTypes,
	}.Build()
	File_codefly_services_builder_v0_deployment_proto = out.File
	file_codefly_services_builder_v0_deployment_proto_goTypes = nil
	file_codefly_services_builder_v0_deployment_proto_depIdxs = nil
}
