// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: codefly/base/v0/application.proto

package v0

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationReference) Reset() {
	*x = ApplicationReference{}
	mi := &file_codefly_base_v0_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationReference) ProtoMessage() {}

func (x *ApplicationReference) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_base_v0_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationReference.ProtoReflect.Descriptor instead.
func (*ApplicationReference) Descriptor() ([]byte, []int) {
	return file_codefly_base_v0_application_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationReference) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

// Application is an end-user facing program (CLI, desktop app, etc.)
// Unlike services, applications don't expose network endpoints
// They produce artifacts (binaries, bundles) and can depend on services and other applications
type Application struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the application
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Short description of the application
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Agent that represents the application
	Agent *Agent `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	// Service dependencies
	ServiceDependencies []*ServiceReference `protobuf:"bytes,4,rep,name=service_dependencies,json=serviceDependencies,proto3" json:"service_dependencies,omitempty"`
	// Application dependencies
	ApplicationDependencies []*ApplicationReference `protobuf:"bytes,5,rep,name=application_dependencies,json=applicationDependencies,proto3" json:"application_dependencies,omitempty"`
	// Build artifacts
	Artifacts     []*Artifact `protobuf:"bytes,6,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_codefly_base_v0_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_base_v0_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_codefly_base_v0_application_proto_rawDescGZIP(), []int{1}
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Application) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *Application) GetServiceDependencies() []*ServiceReference {
	if x != nil {
		return x.ServiceDependencies
	}
	return nil
}

func (x *Application) GetApplicationDependencies() []*ApplicationReference {
	if x != nil {
		return x.ApplicationDependencies
	}
	return nil
}

func (x *Application) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

// Artifact represents a build output from an application
type Artifact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the artifact
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of artifact: "binary", "bundle", "package"
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Target platform: "darwin-arm64", "linux-amd64", etc.
	Platform string `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	// Path to the artifact
	Path          string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_codefly_base_v0_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_base_v0_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_codefly_base_v0_application_proto_rawDescGZIP(), []int{2}
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Artifact) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ApplicationIdentity is the identity of an application in a workspace
type ApplicationIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationIdentity) Reset() {
	*x = ApplicationIdentity{}
	mi := &file_codefly_base_v0_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationIdentity) ProtoMessage() {}

func (x *ApplicationIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_base_v0_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationIdentity.ProtoReflect.Descriptor instead.
func (*ApplicationIdentity) Descriptor() ([]byte, []int) {
	return file_codefly_base_v0_application_proto_rawDescGZIP(), []int{3}
}

func (x *ApplicationIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationIdentity) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ApplicationIdentity) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ApplicationIdentity) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_codefly_base_v0_application_proto protoreflect.FileDescriptor

const file_codefly_base_v0_application_proto_rawDesc = "" +
	"\n" +
	"!codefly/base/v0/application.proto\x12\x0fcodefly.base.v0\x1a\x1bbuf/validate/validate.proto\x1a\x1bcodefly/base/v0/agent.proto\x1a\x1dcodefly/base/v0/service.proto\"X\n" +
	"\x14ApplicationReference\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x182R\x04name\x12!\n" +
	"\x06module\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x182R\x06module\"\xed\x02\n" +
	"\vApplication\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x182R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12,\n" +
	"\x05agent\x18\x03 \x01(\v2\x16.codefly.base.v0.AgentR\x05agent\x12T\n" +
	"\x14service_dependencies\x18\x04 \x03(\v2!.codefly.base.v0.ServiceReferenceR\x13serviceDependencies\x12`\n" +
	"\x18application_dependencies\x18\x05 \x03(\v2%.codefly.base.v0.ApplicationReferenceR\x17applicationDependencies\x127\n" +
	"\tartifacts\x18\x06 \x03(\v2\x19.codefly.base.v0.ArtifactR\tartifacts\"b\n" +
	"\bArtifact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"\x9a\x01\n" +
	"\x13ApplicationIdentity\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x182R\x04name\x12!\n" +
	"\x06module\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x182R\x06module\x12'\n" +
	"\tworkspace\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x182R\tworkspace\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversionB\xbf\x01\n" +
	"\x13com.codefly.base.v0B\x10ApplicationProtoP\x01Z8github.com/codefly-dev/core/generated/go/codefly/base/v0\xa2\x02\x03CBV\xaa\x02\x0fCodefly.Base.V0\xca\x02\x0fCodefly\\Base\\V0\xe2\x02\x1bCodefly\\Base\\V0\\GPBMetadata\xea\x02\x11Codefly::Base::V0b\x06proto3"

var (
	file_codefly_base_v0_application_proto_rawDescOnce sync.Once
	file_codefly_base_v0_application_proto_rawDescData []byte
)

func file_codefly_base_v0_application_proto_rawDescGZIP() []byte {
	file_codefly_base_v0_application_proto_rawDescOnce.Do(func() {
		file_codefly_base_v0_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codefly_base_v0_application_proto_rawDesc), len(file_codefly_base_v0_application_proto_rawDesc)))
	})
	return file_codefly_base_v0_application_proto_rawDescData
}

var file_codefly_base_v0_application_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_codefly_base_v0_application_proto_goTypes = []any{
	(*ApplicationReference)(nil), // 0: codefly.base.v0.ApplicationReference
	(*Application)(nil),          // 1: codefly.base.v0.Application
	(*Artifact)(nil),             // 2: codefly.base.v0.Artifact
	(*ApplicationIdentity)(nil),  // 3: codefly.base.v0.ApplicationIdentity
	(*Agent)(nil),                // 4: codefly.base.v0.Agent
	(*ServiceReference)(nil),     // 5: codefly.base.v0.ServiceReference
}
var file_codefly_base_v0_application_proto_depIdxs = []int32{
	4, // 0: codefly.base.v0.Application.agent:type_name -> codefly.base.v0.Agent
	5, // 1: codefly.base.v0.Application.service_dependencies:type_name -> codefly.base.v0.ServiceReference
	0, // 2: codefly.base.v0.Application.application_dependencies:type_name -> codefly.base.v0.ApplicationReference
	2, // 3: codefly.base.v0.Application.artifacts:type_name -> codefly.base.v0.Artifact
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_codefly_base_v0_application_proto_init() }
func file_codefly_base_v0_application_proto_init() {
	if File_codefly_base_v0_application_proto != nil {
		return
	}
	file_codefly_base_v0_agent_proto_init()
	file_codefly_base_v0_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codefly_base_v0_application_proto_rawDesc), len(file_codefly_base_v0_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codefly_base_v0_application_proto_goTypes,
		DependencyIndexes: file_codefly_base_v0_application_proto_depIdxs,
		MessageInfos:      file_codefly_base_v0_application_proto_msgTypes,
	}.Build()
	File_codefly_base_v0_application_proto = out.File
	file_codefly_base_v0_application_proto_goTypes = nil
	file_codefly_base_v0_application_proto_depIdxs = nil
}
