// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: codefly/base/v0/configuration.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigurationValue is one key/value pair produced by a service or workspace configuration
// source.
type ConfigurationValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is the configuration or schema property name.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// value is the configuration or schema value.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// secret marks configuration values that must not be logged or displayed.
	Secret        bool `protobuf:"varint,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationValue) Reset() {
	*x = ConfigurationValue{}
	mi := &file_codefly_base_v0_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationValue) ProtoMessage() {}

func (x *ConfigurationValue) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_base_v0_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationValue.ProtoReflect.Descriptor instead.
func (*ConfigurationValue) Descriptor() ([]byte, []int) {
	return file_codefly_base_v0_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigurationValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigurationValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigurationValue) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

// ConfigurationData carries a structured configuration blob alongside key/value configuration.
type ConfigurationData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind identifies the format or producer-specific type of this configuration blob.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// content is the full file, resource, prompt, or response body.
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// secret marks configuration values that must not be logged or displayed.
	Secret        bool `protobuf:"varint,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationData) Reset() {
	*x = ConfigurationData{}
	mi := &file_codefly_base_v0_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationData) ProtoMessage() {}

func (x *ConfigurationData) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_base_v0_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationData.ProtoReflect.Descriptor instead.
func (*ConfigurationData) Descriptor() ([]byte, []int) {
	return file_codefly_base_v0_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigurationData) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ConfigurationData) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ConfigurationData) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

// ConfigurationInformation groups named configuration values produced by a service or workspace.
type ConfigurationInformation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the configuration group name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// configuration_values are key/value pairs exposed by a configuration entry.
	ConfigurationValues []*ConfigurationValue `protobuf:"bytes,2,rep,name=configuration_values,json=configurationValues,proto3" json:"configuration_values,omitempty"`
	// data is an optional structured configuration payload for values that do not fit key/value pairs.
	Data          *ConfigurationData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationInformation) Reset() {
	*x = ConfigurationInformation{}
	mi := &file_codefly_base_v0_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationInformation) ProtoMessage() {}

func (x *ConfigurationInformation) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_base_v0_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationInformation.ProtoReflect.Descriptor instead.
func (*ConfigurationInformation) Descriptor() ([]byte, []int) {
	return file_codefly_base_v0_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigurationInformation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigurationInformation) GetConfigurationValues() []*ConfigurationValue {
	if x != nil {
		return x.ConfigurationValues
	}
	return nil
}

func (x *ConfigurationInformation) GetData() *ConfigurationData {
	if x != nil {
		return x.Data
	}
	return nil
}

// Configuration can come from
// - workspace: origin is _workspace
// - service: origin is the service unique
// Information is a grouping of configuration values
type Configuration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// origin identifies the service or workspace that produced the configuration.
	Origin string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	// runtime_context describes where the service runs, such as native, nix, container, or free.
	RuntimeContext *RuntimeContext `protobuf:"bytes,2,opt,name=runtime_context,json=runtimeContext,proto3" json:"runtime_context,omitempty"`
	// infos are named configuration groups exposed by a producer.
	Infos         []*ConfigurationInformation `protobuf:"bytes,3,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_codefly_base_v0_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_base_v0_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_codefly_base_v0_configuration_proto_rawDescGZIP(), []int{3}
}

func (x *Configuration) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Configuration) GetRuntimeContext() *RuntimeContext {
	if x != nil {
		return x.RuntimeContext
	}
	return nil
}

func (x *Configuration) GetInfos() []*ConfigurationInformation {
	if x != nil {
		return x.Infos
	}
	return nil
}

var File_codefly_base_v0_configuration_proto protoreflect.FileDescriptor

const file_codefly_base_v0_configuration_proto_rawDesc = "" +
	"\n" +
	"#codefly/base/v0/configuration.proto\x12\x0fcodefly.base.v0\x1a\x1bcodefly/base/v0/scope.proto\"T\n" +
	"\x12ConfigurationValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\bR\x06secret\"Y\n" +
	"\x11ConfigurationData\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\bR\x06secret\"\xbe\x01\n" +
	"\x18ConfigurationInformation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12V\n" +
	"\x14configuration_values\x18\x02 \x03(\v2#.codefly.base.v0.ConfigurationValueR\x13configurationValues\x126\n" +
	"\x04data\x18\x03 \x01(\v2\".codefly.base.v0.ConfigurationDataR\x04data\"\xb2\x01\n" +
	"\rConfiguration\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12H\n" +
	"\x0fruntime_context\x18\x02 \x01(\v2\x1f.codefly.base.v0.RuntimeContextR\x0eruntimeContext\x12?\n" +
	"\x05infos\x18\x03 \x03(\v2).codefly.base.v0.ConfigurationInformationR\x05infosB\xc1\x01\n" +
	"\x13com.codefly.base.v0B\x12ConfigurationProtoP\x01Z8github.com/codefly-dev/core/generated/go/codefly/base/v0\xa2\x02\x03CBV\xaa\x02\x0fCodefly.Base.V0\xca\x02\x0fCodefly\\Base\\V0\xe2\x02\x1bCodefly\\Base\\V0\\GPBMetadata\xea\x02\x11Codefly::Base::V0b\x06proto3"

var (
	file_codefly_base_v0_configuration_proto_rawDescOnce sync.Once
	file_codefly_base_v0_configuration_proto_rawDescData []byte
)

func file_codefly_base_v0_configuration_proto_rawDescGZIP() []byte {
	file_codefly_base_v0_configuration_proto_rawDescOnce.Do(func() {
		file_codefly_base_v0_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codefly_base_v0_configuration_proto_rawDesc), len(file_codefly_base_v0_configuration_proto_rawDesc)))
	})
	return file_codefly_base_v0_configuration_proto_rawDescData
}

var file_codefly_base_v0_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_codefly_base_v0_configuration_proto_goTypes = []any{
	(*ConfigurationValue)(nil),       // 0: codefly.base.v0.ConfigurationValue
	(*ConfigurationData)(nil),        // 1: codefly.base.v0.ConfigurationData
	(*ConfigurationInformation)(nil), // 2: codefly.base.v0.ConfigurationInformation
	(*Configuration)(nil),            // 3: codefly.base.v0.Configuration
	(*RuntimeContext)(nil),           // 4: codefly.base.v0.RuntimeContext
}
var file_codefly_base_v0_configuration_proto_depIdxs = []int32{
	0, // 0: codefly.base.v0.ConfigurationInformation.configuration_values:type_name -> codefly.base.v0.ConfigurationValue
	1, // 1: codefly.base.v0.ConfigurationInformation.data:type_name -> codefly.base.v0.ConfigurationData
	4, // 2: codefly.base.v0.Configuration.runtime_context:type_name -> codefly.base.v0.RuntimeContext
	2, // 3: codefly.base.v0.Configuration.infos:type_name -> codefly.base.v0.ConfigurationInformation
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_codefly_base_v0_configuration_proto_init() }
func file_codefly_base_v0_configuration_proto_init() {
	if File_codefly_base_v0_configuration_proto != nil {
		return
	}
	file_codefly_base_v0_scope_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codefly_base_v0_configuration_proto_rawDesc), len(file_codefly_base_v0_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codefly_base_v0_configuration_proto_goTypes,
		DependencyIndexes: file_codefly_base_v0_configuration_proto_depIdxs,
		MessageInfos:      file_codefly_base_v0_configuration_proto_msgTypes,
	}.Build()
	File_codefly_base_v0_configuration_proto = out.File
	file_codefly_base_v0_configuration_proto_goTypes = nil
	file_codefly_base_v0_configuration_proto_depIdxs = nil
}
