// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: codefly/base/v0/scope.proto

package v0

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RuntimeContext is used to define the scope of a runtime resource
	// - "free" lets the runtime decide the scope
	// - "container" scope should be used inside containers
	// - "native" scope should be used when running "natively" on the host
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Name enables to "tag" the runtime context: useful for test
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeContext) Reset() {
	*x = RuntimeContext{}
	mi := &file_codefly_base_v0_scope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeContext) ProtoMessage() {}

func (x *RuntimeContext) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_base_v0_scope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeContext.ProtoReflect.Descriptor instead.
func (*RuntimeContext) Descriptor() ([]byte, []int) {
	return file_codefly_base_v0_scope_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeContext) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RuntimeContext) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NetworkAccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NetworkContext is used to define
	// - "container" should be used to access system resources inside containers
	// - "native scope should be used to access system resources from the host
	// - "public" scope should be used when this should be accessible outside of the system
	Kind          string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAccess) Reset() {
	*x = NetworkAccess{}
	mi := &file_codefly_base_v0_scope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAccess) ProtoMessage() {}

func (x *NetworkAccess) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_base_v0_scope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAccess.ProtoReflect.Descriptor instead.
func (*NetworkAccess) Descriptor() ([]byte, []int) {
	return file_codefly_base_v0_scope_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkAccess) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

var File_codefly_base_v0_scope_proto protoreflect.FileDescriptor

const file_codefly_base_v0_scope_proto_rawDesc = "" +
	"\n" +
	"\x1bcodefly/base/v0/scope.proto\x12\x0fcodefly.base.v0\x1a\x1bbuf/validate/validate.proto\"X\n" +
	"\x0eRuntimeContext\x122\n" +
	"\x04kind\x18\x01 \x01(\tB\x1e\xbaH\x1br\x19R\x04freeR\tcontainerR\x06nativeR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"E\n" +
	"\rNetworkAccess\x124\n" +
	"\x04kind\x18\x01 \x01(\tB \xbaH\x1dr\x1bR\tcontainerR\x06nativeR\x06publicR\x04kindB\xb9\x01\n" +
	"\x13com.codefly.base.v0B\n" +
	"ScopeProtoP\x01Z8github.com/codefly-dev/core/generated/go/codefly/base/v0\xa2\x02\x03CBV\xaa\x02\x0fCodefly.Base.V0\xca\x02\x0fCodefly\\Base\\V0\xe2\x02\x1bCodefly\\Base\\V0\\GPBMetadata\xea\x02\x11Codefly::Base::V0b\x06proto3"

var (
	file_codefly_base_v0_scope_proto_rawDescOnce sync.Once
	file_codefly_base_v0_scope_proto_rawDescData []byte
)

func file_codefly_base_v0_scope_proto_rawDescGZIP() []byte {
	file_codefly_base_v0_scope_proto_rawDescOnce.Do(func() {
		file_codefly_base_v0_scope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codefly_base_v0_scope_proto_rawDesc), len(file_codefly_base_v0_scope_proto_rawDesc)))
	})
	return file_codefly_base_v0_scope_proto_rawDescData
}

var file_codefly_base_v0_scope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_codefly_base_v0_scope_proto_goTypes = []any{
	(*RuntimeContext)(nil), // 0: codefly.base.v0.RuntimeContext
	(*NetworkAccess)(nil),  // 1: codefly.base.v0.NetworkAccess
}
var file_codefly_base_v0_scope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_codefly_base_v0_scope_proto_init() }
func file_codefly_base_v0_scope_proto_init() {
	if File_codefly_base_v0_scope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codefly_base_v0_scope_proto_rawDesc), len(file_codefly_base_v0_scope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codefly_base_v0_scope_proto_goTypes,
		DependencyIndexes: file_codefly_base_v0_scope_proto_depIdxs,
		MessageInfos:      file_codefly_base_v0_scope_proto_msgTypes,
	}.Build()
	File_codefly_base_v0_scope_proto = out.File
	file_codefly_base_v0_scope_proto_goTypes = nil
	file_codefly_base_v0_scope_proto_depIdxs = nil
}
