# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from codefly.services.tooling.v0 import tooling_pb2 as codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2


class ToolingStub(object):
    """── Service Definition ─────────────────────────────────

    Tooling provides language-specific code operations.
    Every language agent (go-grpc, python-fastapi, etc.) implements this service.

    NOTE: File operations (read, write, list, search) and git operations are
    NOT part of this service. Mind handles those directly via its VFS.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSymbols = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/ListSymbols',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ListSymbolsRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ListSymbolsResponse.FromString,
                _registered_method=True)
        self.GetDiagnostics = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/GetDiagnostics',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetDiagnosticsRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetDiagnosticsResponse.FromString,
                _registered_method=True)
        self.GoToDefinition = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/GoToDefinition',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GoToDefinitionRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GoToDefinitionResponse.FromString,
                _registered_method=True)
        self.FindReferences = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/FindReferences',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.FindReferencesRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.FindReferencesResponse.FromString,
                _registered_method=True)
        self.RenameSymbol = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/RenameSymbol',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.RenameSymbolRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.RenameSymbolResponse.FromString,
                _registered_method=True)
        self.GetHoverInfo = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/GetHoverInfo',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetHoverInfoRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetHoverInfoResponse.FromString,
                _registered_method=True)
        self.GetCompletions = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/GetCompletions',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetCompletionsRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetCompletionsResponse.FromString,
                _registered_method=True)
        self.Fix = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/Fix',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.FixRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.FixResponse.FromString,
                _registered_method=True)
        self.ApplyEdit = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/ApplyEdit',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ApplyEditRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ApplyEditResponse.FromString,
                _registered_method=True)
        self.ListDependencies = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/ListDependencies',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ListDependenciesRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ListDependenciesResponse.FromString,
                _registered_method=True)
        self.AddDependency = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/AddDependency',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.AddDependencyRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.AddDependencyResponse.FromString,
                _registered_method=True)
        self.RemoveDependency = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/RemoveDependency',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.RemoveDependencyRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.RemoveDependencyResponse.FromString,
                _registered_method=True)
        self.GetProjectInfo = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/GetProjectInfo',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetProjectInfoRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetProjectInfoResponse.FromString,
                _registered_method=True)
        self.GetCallGraph = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/GetCallGraph',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetCallGraphRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetCallGraphResponse.FromString,
                _registered_method=True)
        self.Build = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/Build',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.BuildRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.BuildResponse.FromString,
                _registered_method=True)
        self.Test = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/Test',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.TestRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.TestResponse.FromString,
                _registered_method=True)
        self.Lint = channel.unary_unary(
                '/codefly.services.tooling.v0.Tooling/Lint',
                request_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.LintRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.LintResponse.FromString,
                _registered_method=True)


class ToolingServicer(object):
    """── Service Definition ─────────────────────────────────

    Tooling provides language-specific code operations.
    Every language agent (go-grpc, python-fastapi, etc.) implements this service.

    NOTE: File operations (read, write, list, search) and git operations are
    NOT part of this service. Mind handles those directly via its VFS.
    """

    def ListSymbols(self, request, context):
        """LSP operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDiagnostics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GoToDefinition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindReferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameSymbol(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHoverInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompletions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fix(self, request, context):
        """Code modification
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyEdit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDependencies(self, request, context):
        """Dependency management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDependency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveDependency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectInfo(self, request, context):
        """Analysis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCallGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Build(self, request, context):
        """Dev validation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Test(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSymbols': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSymbols,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ListSymbolsRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ListSymbolsResponse.SerializeToString,
            ),
            'GetDiagnostics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDiagnostics,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetDiagnosticsRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetDiagnosticsResponse.SerializeToString,
            ),
            'GoToDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.GoToDefinition,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GoToDefinitionRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GoToDefinitionResponse.SerializeToString,
            ),
            'FindReferences': grpc.unary_unary_rpc_method_handler(
                    servicer.FindReferences,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.FindReferencesRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.FindReferencesResponse.SerializeToString,
            ),
            'RenameSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameSymbol,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.RenameSymbolRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.RenameSymbolResponse.SerializeToString,
            ),
            'GetHoverInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHoverInfo,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetHoverInfoRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetHoverInfoResponse.SerializeToString,
            ),
            'GetCompletions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompletions,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetCompletionsRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetCompletionsResponse.SerializeToString,
            ),
            'Fix': grpc.unary_unary_rpc_method_handler(
                    servicer.Fix,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.FixRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.FixResponse.SerializeToString,
            ),
            'ApplyEdit': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyEdit,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ApplyEditRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ApplyEditResponse.SerializeToString,
            ),
            'ListDependencies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDependencies,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ListDependenciesRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ListDependenciesResponse.SerializeToString,
            ),
            'AddDependency': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDependency,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.AddDependencyRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.AddDependencyResponse.SerializeToString,
            ),
            'RemoveDependency': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveDependency,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.RemoveDependencyRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.RemoveDependencyResponse.SerializeToString,
            ),
            'GetProjectInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectInfo,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetProjectInfoRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetProjectInfoResponse.SerializeToString,
            ),
            'GetCallGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCallGraph,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetCallGraphRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetCallGraphResponse.SerializeToString,
            ),
            'Build': grpc.unary_unary_rpc_method_handler(
                    servicer.Build,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.BuildRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.BuildResponse.SerializeToString,
            ),
            'Test': grpc.unary_unary_rpc_method_handler(
                    servicer.Test,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.TestRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.TestResponse.SerializeToString,
            ),
            'Lint': grpc.unary_unary_rpc_method_handler(
                    servicer.Lint,
                    request_deserializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.LintRequest.FromString,
                    response_serializer=codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.LintResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'codefly.services.tooling.v0.Tooling', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('codefly.services.tooling.v0.Tooling', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Tooling(object):
    """── Service Definition ─────────────────────────────────

    Tooling provides language-specific code operations.
    Every language agent (go-grpc, python-fastapi, etc.) implements this service.

    NOTE: File operations (read, write, list, search) and git operations are
    NOT part of this service. Mind handles those directly via its VFS.
    """

    @staticmethod
    def ListSymbols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/ListSymbols',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ListSymbolsRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ListSymbolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/GetDiagnostics',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetDiagnosticsRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetDiagnosticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GoToDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/GoToDefinition',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GoToDefinitionRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GoToDefinitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindReferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/FindReferences',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.FindReferencesRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.FindReferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/RenameSymbol',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.RenameSymbolRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.RenameSymbolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHoverInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/GetHoverInfo',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetHoverInfoRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetHoverInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCompletions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/GetCompletions',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetCompletionsRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetCompletionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/Fix',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.FixRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.FixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyEdit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/ApplyEdit',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ApplyEditRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ApplyEditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDependencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/ListDependencies',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ListDependenciesRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.ListDependenciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddDependency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/AddDependency',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.AddDependencyRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.AddDependencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveDependency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/RemoveDependency',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.RemoveDependencyRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.RemoveDependencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/GetProjectInfo',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetProjectInfoRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetProjectInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCallGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/GetCallGraph',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetCallGraphRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.GetCallGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Build(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/Build',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.BuildRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.BuildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/Test',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.TestRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.TestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.tooling.v0.Tooling/Lint',
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.LintRequest.SerializeToString,
            codefly_dot_services_dot_tooling_dot_v0_dot_tooling__pb2.LintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
