# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from codefly.services.toolbox.v0 import toolbox_pb2 as codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2


class ToolboxStub(object):
    """Toolbox is the codefly toolbox contract.

    Vocabulary mirrors the Model Context Protocol (MCP) so that an MCP
    transcoder is a thin wrapper rather than a redesign. The three host-
    facing primitives are:

    Tool      — model-callable function. Input + Output schemas as JSON
    Schema. Side-effecting; gated by the toolbox's policy.
    Resource  — addressable read-only context (a file, a query result,
    a config blob). The agent reads; the toolbox decides what
    to expose.
    Prompt    — parametric message template. Pre-baked instructions the
    agent can fill and run.

    Identity returns the toolbox's name/version/permissions for
    diagnostics and policy decisions; it's the "who am I and what do I
    claim" surface.

    Roots are the MCP boundary primitive — the host (codefly) tells the
    toolbox which directories/URIs it may operate over. We surface this
    as a request field on tool calls rather than a separate RPC; the
    toolbox enforces (with help from the OS sandbox).

    Connect-RPC is the transport — same proto, two encodings (gRPC +
    Connect's HTTP/JSON). Lets us expose toolboxes over HTTP for
    browser-based agents without a second contract.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Identity = channel.unary_unary(
                '/codefly.services.toolbox.v0.Toolbox/Identity',
                request_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.IdentityRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.IdentityResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/codefly.services.toolbox.v0.Toolbox/ListTools',
                request_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.CallTool = channel.unary_unary(
                '/codefly.services.toolbox.v0.Toolbox/CallTool',
                request_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.CallToolRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.CallToolResponse.FromString,
                _registered_method=True)
        self.ListResources = channel.unary_unary(
                '/codefly.services.toolbox.v0.Toolbox/ListResources',
                request_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListResourcesRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListResourcesResponse.FromString,
                _registered_method=True)
        self.ReadResource = channel.unary_unary(
                '/codefly.services.toolbox.v0.Toolbox/ReadResource',
                request_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ReadResourceRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ReadResourceResponse.FromString,
                _registered_method=True)
        self.ListPrompts = channel.unary_unary(
                '/codefly.services.toolbox.v0.Toolbox/ListPrompts',
                request_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListPromptsRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListPromptsResponse.FromString,
                _registered_method=True)
        self.GetPrompt = channel.unary_unary(
                '/codefly.services.toolbox.v0.Toolbox/GetPrompt',
                request_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.GetPromptRequest.SerializeToString,
                response_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.GetPromptResponse.FromString,
                _registered_method=True)


class ToolboxServicer(object):
    """Toolbox is the codefly toolbox contract.

    Vocabulary mirrors the Model Context Protocol (MCP) so that an MCP
    transcoder is a thin wrapper rather than a redesign. The three host-
    facing primitives are:

    Tool      — model-callable function. Input + Output schemas as JSON
    Schema. Side-effecting; gated by the toolbox's policy.
    Resource  — addressable read-only context (a file, a query result,
    a config blob). The agent reads; the toolbox decides what
    to expose.
    Prompt    — parametric message template. Pre-baked instructions the
    agent can fill and run.

    Identity returns the toolbox's name/version/permissions for
    diagnostics and policy decisions; it's the "who am I and what do I
    claim" surface.

    Roots are the MCP boundary primitive — the host (codefly) tells the
    toolbox which directories/URIs it may operate over. We surface this
    as a request field on tool calls rather than a separate RPC; the
    toolbox enforces (with help from the OS sandbox).

    Connect-RPC is the transport — same proto, two encodings (gRPC +
    Connect's HTTP/JSON). Lets us expose toolboxes over HTTP for
    browser-based agents without a second contract.
    """

    def Identity(self, request, context):
        """Identity returns the toolbox's manifest-derived metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """ListTools returns every tool this toolbox exposes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallTool(self, request, context):
        """CallTool invokes a tool by name with structured arguments.
        The result carries either a Content payload, an error, or both
        (e.g. partial success + warnings).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResources(self, request, context):
        """ListResources returns every addressable resource the toolbox
        exposes for read-only context.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadResource(self, request, context):
        """ReadResource fetches a resource's content by URI.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPrompts(self, request, context):
        """ListPrompts returns every parametric prompt template the toolbox
        exposes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrompt(self, request, context):
        """GetPrompt renders a prompt with the supplied arguments.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolboxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Identity': grpc.unary_unary_rpc_method_handler(
                    servicer.Identity,
                    request_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.IdentityRequest.FromString,
                    response_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.IdentityResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListToolsRequest.FromString,
                    response_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListToolsResponse.SerializeToString,
            ),
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.CallToolRequest.FromString,
                    response_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.CallToolResponse.SerializeToString,
            ),
            'ListResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResources,
                    request_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListResourcesRequest.FromString,
                    response_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListResourcesResponse.SerializeToString,
            ),
            'ReadResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadResource,
                    request_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ReadResourceRequest.FromString,
                    response_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ReadResourceResponse.SerializeToString,
            ),
            'ListPrompts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPrompts,
                    request_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListPromptsRequest.FromString,
                    response_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListPromptsResponse.SerializeToString,
            ),
            'GetPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrompt,
                    request_deserializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.GetPromptRequest.FromString,
                    response_serializer=codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.GetPromptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'codefly.services.toolbox.v0.Toolbox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('codefly.services.toolbox.v0.Toolbox', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Toolbox(object):
    """Toolbox is the codefly toolbox contract.

    Vocabulary mirrors the Model Context Protocol (MCP) so that an MCP
    transcoder is a thin wrapper rather than a redesign. The three host-
    facing primitives are:

    Tool      — model-callable function. Input + Output schemas as JSON
    Schema. Side-effecting; gated by the toolbox's policy.
    Resource  — addressable read-only context (a file, a query result,
    a config blob). The agent reads; the toolbox decides what
    to expose.
    Prompt    — parametric message template. Pre-baked instructions the
    agent can fill and run.

    Identity returns the toolbox's name/version/permissions for
    diagnostics and policy decisions; it's the "who am I and what do I
    claim" surface.

    Roots are the MCP boundary primitive — the host (codefly) tells the
    toolbox which directories/URIs it may operate over. We surface this
    as a request field on tool calls rather than a separate RPC; the
    toolbox enforces (with help from the OS sandbox).

    Connect-RPC is the transport — same proto, two encodings (gRPC +
    Connect's HTTP/JSON). Lets us expose toolboxes over HTTP for
    browser-based agents without a second contract.
    """

    @staticmethod
    def Identity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.toolbox.v0.Toolbox/Identity',
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.IdentityRequest.SerializeToString,
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.IdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.toolbox.v0.Toolbox/ListTools',
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListToolsRequest.SerializeToString,
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.toolbox.v0.Toolbox/CallTool',
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.CallToolRequest.SerializeToString,
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.CallToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.toolbox.v0.Toolbox/ListResources',
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListResourcesRequest.SerializeToString,
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.toolbox.v0.Toolbox/ReadResource',
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ReadResourceRequest.SerializeToString,
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ReadResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPrompts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.toolbox.v0.Toolbox/ListPrompts',
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListPromptsRequest.SerializeToString,
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.ListPromptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.services.toolbox.v0.Toolbox/GetPrompt',
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.GetPromptRequest.SerializeToString,
            codefly_dot_services_dot_toolbox_dot_v0_dot_toolbox__pb2.GetPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
