// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: codefly/observability/v0/sessions.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkspaceSnapshot captures workspace identity at the time a session was recorded.
type WorkspaceSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid is the durable identifier for the snapshot or session.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// name is the workspace name captured in this snapshot.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceSnapshot) Reset() {
	*x = WorkspaceSnapshot{}
	mi := &file_codefly_observability_v0_sessions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceSnapshot) ProtoMessage() {}

func (x *WorkspaceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_observability_v0_sessions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceSnapshot.ProtoReflect.Descriptor instead.
func (*WorkspaceSnapshot) Descriptor() ([]byte, []int) {
	return file_codefly_observability_v0_sessions_proto_rawDescGZIP(), []int{0}
}

func (x *WorkspaceSnapshot) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *WorkspaceSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ModuleSnapshot captures module identity and its workspace snapshot.
type ModuleSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid is the durable identifier for the snapshot or session.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// name is the module name captured in this snapshot.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// workspace is the Codefly workspace name that scopes modules and services.
	Workspace     *WorkspaceSnapshot `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleSnapshot) Reset() {
	*x = ModuleSnapshot{}
	mi := &file_codefly_observability_v0_sessions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleSnapshot) ProtoMessage() {}

func (x *ModuleSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_observability_v0_sessions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleSnapshot.ProtoReflect.Descriptor instead.
func (*ModuleSnapshot) Descriptor() ([]byte, []int) {
	return file_codefly_observability_v0_sessions_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleSnapshot) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ModuleSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleSnapshot) GetWorkspace() *WorkspaceSnapshot {
	if x != nil {
		return x.Workspace
	}
	return nil
}

// PartialSnapshot captures a workspace and the modules known for a recorded session.
type PartialSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid is the durable identifier for the snapshot or session.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// name is the snapshot display name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// workspace is the Codefly workspace name that scopes modules and services.
	Workspace *WorkspaceSnapshot `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	// modules are the module snapshots known at this point in time.
	Modules       []*ModuleSnapshot `protobuf:"bytes,4,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialSnapshot) Reset() {
	*x = PartialSnapshot{}
	mi := &file_codefly_observability_v0_sessions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialSnapshot) ProtoMessage() {}

func (x *PartialSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_observability_v0_sessions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialSnapshot.ProtoReflect.Descriptor instead.
func (*PartialSnapshot) Descriptor() ([]byte, []int) {
	return file_codefly_observability_v0_sessions_proto_rawDescGZIP(), []int{2}
}

func (x *PartialSnapshot) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PartialSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PartialSnapshot) GetWorkspace() *WorkspaceSnapshot {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *PartialSnapshot) GetModules() []*ModuleSnapshot {
	if x != nil {
		return x.Modules
	}
	return nil
}

// Session records a point-in-time workspace/module snapshot.
type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid is the durable identifier for the snapshot or session.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// at is the timestamp for the log or session snapshot.
	At *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	// session selects the snapshot granularity recorded for this session.
	//
	// Types that are valid to be assigned to Session:
	//
	//	*Session_Partial
	//	*Session_Module
	Session       isSession_Session `protobuf_oneof:"session"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_codefly_observability_v0_sessions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_codefly_observability_v0_sessions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_codefly_observability_v0_sessions_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Session) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *Session) GetSession() isSession_Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *Session) GetPartial() *PartialSnapshot {
	if x != nil {
		if x, ok := x.Session.(*Session_Partial); ok {
			return x.Partial
		}
	}
	return nil
}

func (x *Session) GetModule() *ModuleSnapshot {
	if x != nil {
		if x, ok := x.Session.(*Session_Module); ok {
			return x.Module
		}
	}
	return nil
}

type isSession_Session interface {
	isSession_Session()
}

type Session_Partial struct {
	// partial carries the PartialSnapshot variant for Session.
	Partial *PartialSnapshot `protobuf:"bytes,3,opt,name=partial,proto3,oneof"`
}

type Session_Module struct {
	// module carries a module-level snapshot.
	Module *ModuleSnapshot `protobuf:"bytes,4,opt,name=module,proto3,oneof"`
}

func (*Session_Partial) isSession_Session() {}

func (*Session_Module) isSession_Session() {}

var File_codefly_observability_v0_sessions_proto protoreflect.FileDescriptor

const file_codefly_observability_v0_sessions_proto_rawDesc = "" +
	"\n" +
	"'codefly/observability/v0/sessions.proto\x12\x18codefly.observability.v0\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\x11WorkspaceSnapshot\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x83\x01\n" +
	"\x0eModuleSnapshot\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12I\n" +
	"\tworkspace\x18\x03 \x01(\v2+.codefly.observability.v0.WorkspaceSnapshotR\tworkspace\"\xc8\x01\n" +
	"\x0fPartialSnapshot\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12I\n" +
	"\tworkspace\x18\x03 \x01(\v2+.codefly.observability.v0.WorkspaceSnapshotR\tworkspace\x12B\n" +
	"\amodules\x18\x04 \x03(\v2(.codefly.observability.v0.ModuleSnapshotR\amodules\"\xdf\x01\n" +
	"\aSession\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12E\n" +
	"\apartial\x18\x03 \x01(\v2).codefly.observability.v0.PartialSnapshotH\x00R\apartial\x12B\n" +
	"\x06module\x18\x04 \x01(\v2(.codefly.observability.v0.ModuleSnapshotH\x00R\x06moduleB\t\n" +
	"\asessionB\xf2\x01\n" +
	"\x1ccom.codefly.observability.v0B\rSessionsProtoP\x01ZAgithub.com/codefly-dev/core/generated/go/codefly/observability/v0\xa2\x02\x03COV\xaa\x02\x18Codefly.Observability.V0\xca\x02\x18Codefly\\Observability\\V0\xe2\x02$Codefly\\Observability\\V0\\GPBMetadata\xea\x02\x1aCodefly::Observability::V0b\x06proto3"

var (
	file_codefly_observability_v0_sessions_proto_rawDescOnce sync.Once
	file_codefly_observability_v0_sessions_proto_rawDescData []byte
)

func file_codefly_observability_v0_sessions_proto_rawDescGZIP() []byte {
	file_codefly_observability_v0_sessions_proto_rawDescOnce.Do(func() {
		file_codefly_observability_v0_sessions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codefly_observability_v0_sessions_proto_rawDesc), len(file_codefly_observability_v0_sessions_proto_rawDesc)))
	})
	return file_codefly_observability_v0_sessions_proto_rawDescData
}

var file_codefly_observability_v0_sessions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_codefly_observability_v0_sessions_proto_goTypes = []any{
	(*WorkspaceSnapshot)(nil),     // 0: codefly.observability.v0.WorkspaceSnapshot
	(*ModuleSnapshot)(nil),        // 1: codefly.observability.v0.ModuleSnapshot
	(*PartialSnapshot)(nil),       // 2: codefly.observability.v0.PartialSnapshot
	(*Session)(nil),               // 3: codefly.observability.v0.Session
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_codefly_observability_v0_sessions_proto_depIdxs = []int32{
	0, // 0: codefly.observability.v0.ModuleSnapshot.workspace:type_name -> codefly.observability.v0.WorkspaceSnapshot
	0, // 1: codefly.observability.v0.PartialSnapshot.workspace:type_name -> codefly.observability.v0.WorkspaceSnapshot
	1, // 2: codefly.observability.v0.PartialSnapshot.modules:type_name -> codefly.observability.v0.ModuleSnapshot
	4, // 3: codefly.observability.v0.Session.at:type_name -> google.protobuf.Timestamp
	2, // 4: codefly.observability.v0.Session.partial:type_name -> codefly.observability.v0.PartialSnapshot
	1, // 5: codefly.observability.v0.Session.module:type_name -> codefly.observability.v0.ModuleSnapshot
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_codefly_observability_v0_sessions_proto_init() }
func file_codefly_observability_v0_sessions_proto_init() {
	if File_codefly_observability_v0_sessions_proto != nil {
		return
	}
	file_codefly_observability_v0_sessions_proto_msgTypes[3].OneofWrappers = []any{
		(*Session_Partial)(nil),
		(*Session_Module)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codefly_observability_v0_sessions_proto_rawDesc), len(file_codefly_observability_v0_sessions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codefly_observability_v0_sessions_proto_goTypes,
		DependencyIndexes: file_codefly_observability_v0_sessions_proto_depIdxs,
		MessageInfos:      file_codefly_observability_v0_sessions_proto_msgTypes,
	}.Build()
	File_codefly_observability_v0_sessions_proto = out.File
	file_codefly_observability_v0_sessions_proto_goTypes = nil
	file_codefly_observability_v0_sessions_proto_depIdxs = nil
}
