# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from codefly.cli.v0 import terminal_pb2 as codefly_dot_cli_dot_v0_dot_terminal__pb2


class TerminalServiceStub(object):
    """TerminalService provides interactive terminal sessions scoped to workspace/module/service.
    Sessions persist across client disconnections in the server-backed terminal model.
    Attach() is bidirectional streaming — auto-upgrades to WebSocket via grpc-websocket-proxy.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Open = channel.unary_unary(
                '/codefly.cli.v0.TerminalService/Open',
                request_serializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.OpenTerminalRequest.SerializeToString,
                response_deserializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.OpenTerminalResponse.FromString,
                _registered_method=True)
        self.Attach = channel.stream_stream(
                '/codefly.cli.v0.TerminalService/Attach',
                request_serializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.TerminalInput.SerializeToString,
                response_deserializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.TerminalOutput.FromString,
                _registered_method=True)
        self.Resize = channel.unary_unary(
                '/codefly.cli.v0.TerminalService/Resize',
                request_serializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.ResizeTerminalRequest.SerializeToString,
                response_deserializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.ResizeTerminalResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/codefly.cli.v0.TerminalService/Close',
                request_serializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.CloseTerminalRequest.SerializeToString,
                response_deserializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.CloseTerminalResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/codefly.cli.v0.TerminalService/List',
                request_serializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.ListTerminalsRequest.SerializeToString,
                response_deserializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.ListTerminalsResponse.FromString,
                _registered_method=True)


class TerminalServiceServicer(object):
    """TerminalService provides interactive terminal sessions scoped to workspace/module/service.
    Sessions persist across client disconnections in the server-backed terminal model.
    Attach() is bidirectional streaming — auto-upgrades to WebSocket via grpc-websocket-proxy.
    """

    def Open(self, request, context):
        """Open creates a new PTY-backed terminal session scoped to the requested workspace context.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attach(self, request_iterator, context):
        """Attach streams raw input bytes to the PTY and raw output bytes back to the client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resize(self, request, context):
        """Resize changes the PTY dimensions for an active terminal session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Close terminates an active terminal session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """List returns active terminal sessions known to the CLI server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TerminalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.OpenTerminalRequest.FromString,
                    response_serializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.OpenTerminalResponse.SerializeToString,
            ),
            'Attach': grpc.stream_stream_rpc_method_handler(
                    servicer.Attach,
                    request_deserializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.TerminalInput.FromString,
                    response_serializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.TerminalOutput.SerializeToString,
            ),
            'Resize': grpc.unary_unary_rpc_method_handler(
                    servicer.Resize,
                    request_deserializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.ResizeTerminalRequest.FromString,
                    response_serializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.ResizeTerminalResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.CloseTerminalRequest.FromString,
                    response_serializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.CloseTerminalResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.ListTerminalsRequest.FromString,
                    response_serializer=codefly_dot_cli_dot_v0_dot_terminal__pb2.ListTerminalsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'codefly.cli.v0.TerminalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('codefly.cli.v0.TerminalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TerminalService(object):
    """TerminalService provides interactive terminal sessions scoped to workspace/module/service.
    Sessions persist across client disconnections in the server-backed terminal model.
    Attach() is bidirectional streaming — auto-upgrades to WebSocket via grpc-websocket-proxy.
    """

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.cli.v0.TerminalService/Open',
            codefly_dot_cli_dot_v0_dot_terminal__pb2.OpenTerminalRequest.SerializeToString,
            codefly_dot_cli_dot_v0_dot_terminal__pb2.OpenTerminalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attach(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/codefly.cli.v0.TerminalService/Attach',
            codefly_dot_cli_dot_v0_dot_terminal__pb2.TerminalInput.SerializeToString,
            codefly_dot_cli_dot_v0_dot_terminal__pb2.TerminalOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.cli.v0.TerminalService/Resize',
            codefly_dot_cli_dot_v0_dot_terminal__pb2.ResizeTerminalRequest.SerializeToString,
            codefly_dot_cli_dot_v0_dot_terminal__pb2.ResizeTerminalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.cli.v0.TerminalService/Close',
            codefly_dot_cli_dot_v0_dot_terminal__pb2.CloseTerminalRequest.SerializeToString,
            codefly_dot_cli_dot_v0_dot_terminal__pb2.CloseTerminalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codefly.cli.v0.TerminalService/List',
            codefly_dot_cli_dot_v0_dot_terminal__pb2.ListTerminalsRequest.SerializeToString,
            codefly_dot_cli_dot_v0_dot_terminal__pb2.ListTerminalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
